const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const state={players:6,perPlayer:3,mode:'draft',exp:new Set(['base','pok','codex3','te']),names:[],seed:'',phase:'setup',speakerOrder:[],assignments:[],current:0,picks:[],deal:[],selected:null,guideFilter:'all'};
function initials(name){return name.replace(/^The\s+/,'').split(/\s+/).filter(Boolean).slice(0,2).map(x=>x[0]).join('').replace(/[^A-Z0-9]/gi,'').toUpperCase()||'TI'}
function newSeed(){const a=new Uint32Array(2);crypto.getRandomValues(a);return [...a].map(x=>x.toString(36)).join('-').slice(0,14)}
function hashSeed(str){let h=2166136261>>>0;for(let i=0;i<str.length;i++){h^=str.charCodeAt(i);h=Math.imul(h,16777619)}return h>>>0}
function rngFrom(seed){let a=hashSeed(seed)||1;return()=>{a+=0x6D2B79F5;let t=a;t=Math.imul(t^t>>>15,t|1);t^=t+Math.imul(t^t>>>7,t|61);return((t^t>>>14)>>>0)/4294967296}}
function shuffle(arr,rng=rngFrom(state.seed)){const a=[...arr];for(let i=a.length-1;i>0;i--){const j=Math.floor(rng()*(i+1));[a[i],a[j]]=[a[j],a[i]]}return a}
function playerName(i){return(state.names[i]||'').trim()||`Player ${i+1}`}
function expFactions(){return factions.filter(f=>state.exp.has(f.exp))}
function toast(msg){const el=$('#toast');el.textContent=msg;el.classList.add('show');clearTimeout(toast.t);toast.t=setTimeout(()=>el.classList.remove('show'),1900)}
function setSeed(seed){state.seed=seed||newSeed();$('#seedText').textContent=state.seed}
function renderExpansions(){const counts={};factions.forEach(f=>counts[f.exp]=(counts[f.exp]||0)+1);$('#expGrid').innerHTML=Object.entries(E).map(([id,x])=>`<button class="exp ${state.exp.has(id)?'on':''} ${id==='base'?'locked':''}" data-exp="${id}"><span class="check">${state.exp.has(id)?'✓':''}</span><span class="exp-name">${x.name}</span><span class="exp-meta">${counts[id]} faction${counts[id]===1?'':'s'} • ${id==='base'?'Required':'Optional'}</span></button>`).join('')}
function renderNames(){state.names.length=state.players;$('#names').innerHTML=Array.from({length:state.players},(_,i)=>`<div class="name-wrap"><label>Seat ${i+1}</label><input data-name="${i}" value="${escapeAttr(state.names[i]||'')}" placeholder="Player ${i+1}"></div>`).join('');saveNames()}
function escapeAttr(s){return String(s).replace(/&/g,'&amp;').replace(/"/g,'&quot;').replace(/</g,'&lt;')}
function saveNames(){try{localStorage.setItem('ti4-draft-names',JSON.stringify(state.names))}catch(e){}}
function loadNames(){try{const n=JSON.parse(localStorage.getItem('ti4-draft-names')||'[]');if(Array.isArray(n))state.names=n.slice(0,8)}catch(e){}}
function updateCounts(){state.players=Math.max(2,Math.min(8,state.players));state.perPlayer=Math.max(1,Math.min(5,state.perPlayer));$('#playerCount').textContent=state.players;$('#optionCount').textContent=state.perPlayer;renderNames()}
function artMarkup(f,cls=''){return f.art?`<div class="card-art ${cls}"><img loading="lazy" src="${f.art}" alt="${escapeAttr(f.name)} faction reference art" onerror="this.parentElement.innerHTML='<div class=&quot;sigil-bg&quot;><span>${initials(f.name)}</span></div>'"></div>`:`<div class="sigil-bg ${cls}"><span>${initials(f.name)}</span></div>`}
function factionCard(f,opts={}){return `<article class="faction-card ${opts.selected?'selected':''} ${opts.locked?'locked':''}" data-faction="${escapeAttr(f.name)}" style="--accent:${f.color}">${artMarkup(f)}<div class="top"><span class="badge">${E[f.exp].short}</span><span class="tag">${f.tag}</span></div><div class="card-copy"><div class="faction-name">${f.name}</div><div class="blurb">${f.blurb}</div><div class="select-mark">${opts.guide?'Open Archive':'⬡ Select Faction'}</div></div></article>`}
function renderGuide(){const q=$('#guideSearch').value.trim().toLowerCase();const list=factions.filter(f=>(state.guideFilter==='all'||f.exp===state.guideFilter)&&(!q||`${f.name} ${f.tag} ${f.blurb} ${E[f.exp].name}`.toLowerCase().includes(q)));$('#guideGrid').innerHTML=list.length?list.map(f=>factionCard(f,{guide:true})).join(''):'<div class="empty">No factions match that transmission.</div>'}
function renderFilters(){$('#guideFilters').innerHTML=['all',...Object.keys(E)].map(id=>`<button class="filter ${state.guideFilter===id?'active':''}" data-filter="${id}">${id==='all'?'All':E[id].short}</button>`).join('')}
function switchView(id){$$('.view').forEach(x=>x.classList.toggle('active',x.id===id+'View'));$$('.nav button').forEach(x=>x.classList.toggle('active',x.dataset.view===id));if(id==='guide')renderGuide()}
function openFaction(name){const f=factions.find(x=>x.name===name);if(!f)return;$('#modalBody').innerHTML=`<div class="modal-title">${f.name}</div><div class="modal-meta">${E[f.exp].name} • ${f.tag}</div><div style="color:var(--text);font-size:14px;line-height:1.5;margin-bottom:14px">${f.blurb}</div>${f.art?`<img class="reference-img" src="${f.art}" alt="${escapeAttr(f.name)} faction reference card" onerror="this.outerHTML='<div class=&quot;modal-fallback&quot;>Reference image could not be loaded. The drafter will keep using its built-in sigil fallback.</div>'">`:`<div class="modal-fallback"><div style="font-family:'Cinzel Decorative',serif;font-size:48px;color:${f.color};margin-bottom:12px">${initials(f.name)}</div>No verified remote reference image is linked for this faction yet. The custom sigil is intentional — no broken asset placeholders.</div>`}`;$('#modal').classList.add('open')}
function setupFromUrl(){const p=new URLSearchParams(location.search);if(p.get('seed'))state.seed=p.get('seed').slice(0,40);if(p.get('players'))state.players=+p.get('players')||state.players;if(p.get('per'))state.perPlayer=+p.get('per')||state.perPlayer;if(['draft','random'].includes(p.get('mode')))state.mode=p.get('mode');if(p.get('exp')){const xs=p.get('exp').split(',').filter(x=>E[x]);xs.push('base');state.exp=new Set(xs)}if(p.get('names')){try{const n=JSON.parse(decodeURIComponent(p.get('names')));if(Array.isArray(n))state.names=n.slice(0,8)}catch(e){}}}
function draftUrl(){const p=new URLSearchParams();p.set('seed',state.seed);p.set('players',state.players);p.set('per',state.perPlayer);p.set('mode',state.mode);p.set('exp',[...state.exp].join(','));p.set('names',encodeURIComponent(JSON.stringify(state.names.slice(0,state.players))));return location.origin+location.pathname+'?'+p.toString()}
async function copyText(text,msg){try{await navigator.clipboard.writeText(text);toast(msg)}catch(e){const ta=document.createElement('textarea');ta.value=text;document.body.appendChild(ta);ta.select();document.execCommand('copy');ta.remove();toast(msg)}}
