const COUNCIL_MEMORY_KEY='ti4-council-memory-v1';
const COUNCIL_API='/api/council';
const COUNCIL_FACTION_LINES={
  'The Arborec':['A plant-based strategic decision. The Council will notify the gardening department.','You chose the faction whose solution to every problem is more organism. Disturbing. Efficient. Moist.'],
  'The Barony of Letnev':['Ah yes. Big fleets, bigger confidence, and diplomacy performed through orbital pressure.','The Barony. Because subtlety is for civilizations with smaller flagships.'],
  'The Clan of Saar':['A civilization that looked at home ownership and correctly identified it as a tactical liability.','No planets required. No roots. No landlord. The Council is reluctantly impressed.'],
  'The Embers of Muaat':['You have selected the enormous flaming problem and volunteered to drive it personally.','War Suns at the beginning. Restraint has formally left the chamber.'],
  'The Emirates of Hacan':['Capitalism has entered the chamber wearing fur and asking who wants to make a deal.','Excellent. You may now monetize the table\'s trust before destroying it.'],
  'The Federation of Sol':['Reliable. Flexible. Competent. Disgustingly sensible.','Sol. A strong choice for anyone afraid of making the Council laugh too early.'],
  'The Ghosts of Creuss':['Space has doors now. You intend to use all of them without knocking.','The Council notes your commitment to appearing where nobody invited you.'],
  'The L1Z1X Mindnet':['Ancient murder robots. Clean lines. Efficient fleets. Minimal emotional overhead.','You have selected mechanized resentment as a governing philosophy.'],
  'The Mentak Coalition':['Piracy with paperwork. The Council respects the administrative commitment.','You chose Mentak, so every transaction at the table is now technically a cry for help.'],
  'The Naalu Collective':['Initiative is apparently a suggestion now. Wonderful.','You have selected the faction most likely to make everyone ask whose turn it actually is.'],
  'The Nekro Virus':['Technology through consumption. Peer review has become considerably more violent.','You chose Nekro. Please keep your appendages away from the other players\' research.'],
  'Sardakk N\'orr':['Why research weapons when you can simply be angrier than physics?','The Council has reviewed your technology portfolio. It appears to contain punching.'],
  'The Universities of Jol-Nar':['Ah. Science. Surely nobody will resent you for being better at it than everyone else.','You picked the galaxy\'s most efficient method of turning homework into military superiority.'],
  'The Winnu':['Mecatol Rex has noticed you staring again.','You selected Winnu. There is now only one plan and everyone at the table knows exactly what it is.'],
  'The Xxcha Kingdom':['Diplomacy, fortification, and the quiet confidence of someone planning to say no repeatedly.','You chose Xxcha. The word “veto” has begun warming up backstage.'],
  'The Yin Brotherhood':['Nothing says spiritual conviction like weaponized self-sacrifice.','The Council acknowledges your decision to make every fleet exchange emotionally complicated.'],
  'The Yssaril Tribes':['You have chosen to collect secrets like a raccoon with diplomatic immunity.','Cards, information, patience. The table will hate not knowing what you know.'],
  'The Argent Flight':['Fast destroyers and moral certainty. An exhausting combination.','You have selected border enforcement with wings.'],
  'The Empyrean':['You intend to make friends in empty space. Somehow this is a viable economic model.','Darkness, favors, and suspiciously wholesome diplomacy. The Council remains wary.'],
  'The Mahact Gene-Sorcerers':['You chose the ancient tyrants who collect commanders like trophies. Subtle.','The Council is pleased to see hereditary galactic domination making a comeback.'],
  'The Naaz-Rokha Alliance':['Archaeology, except the artifacts occasionally become combat upgrades.','You have selected the faction most likely to dig through the galaxy\'s couch cushions for legendary technology.'],
  'The Nomad':['A mysterious traveler with money, agents, and absolutely no suspicious backstory whatsoever.','You chose the Nomad. The Council has already lost track of which employee is actually in charge.'],
  'The Titans of Ul':['Ancient sleeping machines underneath planets. Real estate has become hostile.','You picked Titans. Every planet you touch now comes with an alarming warranty.'],
  'The Vuil\'raith Cabal':['You have selected kidnapping as a logistics strategy.','The Cabal. Because destroying enemy ships was apparently not personal enough.']
};
function councilLoadMemory(){try{const x=JSON.parse(localStorage.getItem(COUNCIL_MEMORY_KEY)||'{"events":[],"achievements":{}}');return x&&Array.isArray(x.events)?x:{events:[],achievements:{}}}catch(e){return{events:[],achievements:{}}}}
function councilSaveMemory(m){try{localStorage.setItem(COUNCIL_MEMORY_KEY,JSON.stringify(m))}catch(e){}}
function councilPlayerKey(name){return String(name||'unknown').trim().toLowerCase().replace(/\s+/g,' ')}
function councilHistoryFor(player){const m=councilLoadMemory(),key=councilPlayerKey(player),events=m.events.filter(e=>e.playerKey===key);return{events,total:events.length,factions:events.reduce((a,e)=>(a[e.faction]=(a[e.faction]||0)+1,a),{}),speakerCount:events.filter(e=>e.speaker).length,achievements:m.achievements[key]||[]}}
function councilContext(a,f){const player=playerName(a.playerIdx),history=councilHistoryFor(player);return{seed:state.seed,player,playerKey:councilPlayerKey(player),pickNumber:state.current+1,totalPlayers:state.players,speaker:state.current===0,faction:f.name,tag:f.tag,blurb:f.blurb,expansion:E[f.exp]?.name||f.exp,offered:a.options.map(x=>x.name),rejected:a.options.filter(x=>x.name!==f.name).map(x=>x.name),alreadyPicked:state.picks.map(p=>({player:playerName(p.playerIdx),faction:p.faction.name,pick:p.pos+1})),history:{totalDraftPicks:history.total,factions:history.factions,speakerCount:history.speakerCount,achievements:history.achievements}}}
function councilEventId(ctx){return`${ctx.seed}|${ctx.pickNumber}|${ctx.playerKey}`}
function councilAchievementFor(ctx,afterHistory){const count=afterHistory.factions[ctx.faction]||0;if(count>=3)return{title:'THE DEFINITION OF INSANITY',copy:`Draft ${ctx.faction} three times. Apparently this is a tradition now.`};if(count===2)return{title:'DEJA VU PROTOCOL',copy:`Return to ${ctx.faction}. The Council has begun checking for a stuck button.`};const specials={'The Arborec':['I CAN FIX THEM','Select Arborec voluntarily. Botany has consequences.'],'The Clan of Saar':['HOMELESS BY CHOICE','Reject the concept of a home system as strategically limiting.'],'The Embers of Muaat':['BIG RED BUTTON','Start the evening by making War Suns everyone else\'s problem.'],'The Nekro Virus':['TECH SUPPORT NIGHTMARE','Acquire a research strategy based primarily on violence.'],'The Winnu':['MECATOL OR BUST','Choose a faction with all emotional bandwidth allocated to one planet.'],'The Vuil\'raith Cabal':['FREE RANGE SPACE MONSTERS','Turn enemy plastic into inventory.']};if(specials[ctx.faction])return{title:specials[ctx.faction][0],copy:specials[ctx.faction][1]};if(afterHistory.total===5)return{title:'REPEAT OFFENDER',copy:'Accumulate five recorded faction selections. The file is getting thick.'};if(afterHistory.speakerCount===3&&ctx.speaker)return{title:'THE TOKEN KNOWS YOUR NAME',copy:'Become Speaker three recorded times. Suspicious.'};return null}
function councilRecordPick(ctx){const m=councilLoadMemory(),id=councilEventId(ctx);m.events=m.events.filter(e=>e.id!==id);m.events.push({id,seed:ctx.seed,player:ctx.player,playerKey:ctx.playerKey,faction:ctx.faction,pickNumber:ctx.pickNumber,speaker:ctx.speaker,ts:Date.now()});if(m.events.length>300)m.events=m.events.slice(-300);councilSaveMemory(m);const h=councilHistoryFor(ctx.player),achievement=councilAchievementFor(ctx,h);if(achievement){const mm=councilLoadMemory(),list=mm.achievements[ctx.playerKey]||[];if(!list.some(x=>x.title===achievement.title)){list.push({...achievement,ts:Date.now()});mm.achievements[ctx.playerKey]=list;councilSaveMemory(mm);return achievement}}return null}
function councilForgetPick(id){if(!id)return;const m=councilLoadMemory();m.events=m.events.filter(e=>e.id!==id);councilSaveMemory(m)}
function councilHash(s){let h=2166136261>>>0;for(let i=0;i<s.length;i++){h^=s.charCodeAt(i);h=Math.imul(h,16777619)}return h>>>0}
function councilPick(arr,ctx,salt=''){return arr[councilHash(`${ctx.seed}|${ctx.player}|${ctx.faction}|${salt}`)%arr.length]}
function councilLocalReaction(ctx){const factionLines=COUNCIL_FACTION_LINES[ctx.faction]||[`You selected ${ctx.faction}. The Council has updated the risk register and lowered its expectations accordingly.`,`${ctx.faction}. A choice has been made. Whether it qualifies as judgment remains under review.`,`The chamber acknowledges ${ctx.faction}. Several future apologies have already been pre-approved.`];const first=councilPick(factionLines,ctx,'faction');const rejected=ctx.rejected.length?` You rejected ${ctx.rejected.join(' and ')} to get here. This will be remembered whenever convenient.`:'';const history=ctx.history.totalDraftPicks>0?` Prior recorded selections for ${ctx.player}: ${ctx.history.totalDraftPicks}. The pattern recognition subsystem is becoming interested.`:` No previous violations are on file for ${ctx.player}. Enjoy the temporary anonymity.`;const pickLine=ctx.speaker?'The Speaker has used first priority with all the restraint expected of absolute power.':`Pick ${ctx.pickNumber}. The good excuses are disappearing quickly.`;return `${first}${rejected}\n\n${pickLine}${history}`}
async function councilRemoteReaction(ctx){const controller=new AbortController(),timer=setTimeout(()=>controller.abort(),8000);try{const r=await fetch(COUNCIL_API,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(ctx),signal:controller.signal});let data={};try{data=await r.json()}catch(e){}if(!r.ok){const error=new Error(String(data.code||`http_${r.status}`));error.code=String(data.code||`http_${r.status}`);throw error}const text=String(data.commentary||'').trim();if(!text){const error=new Error('empty_response');error.code='empty_response';throw error}return{text,source:'llm'}}finally{clearTimeout(timer)}}
function prepareCouncilReaction(a,f){const ctx=councilContext(a,f),local=councilLocalReaction(ctx);const promise=councilRemoteReaction(ctx).catch(error=>({text:local,source:'local',reason:error?.name==='AbortError'?'timeout':String(error?.code||error?.message||'uplink_failed')}));return{ctx,promise}}
function councilEscape(s){return String(s||'').replace(/[&<>"']/g,ch=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[ch]))}
function councilIntelSound(){try{ensureAudio();const t=audioCtx.currentTime,o=audioCtx.createOscillator(),g=audioCtx.createGain(),f=audioCtx.createBiquadFilter();o.type='triangle';o.frequency.setValueAtTime(71,t);o.frequency.exponentialRampToValueAtTime(43,t+.7);f.type='lowpass';f.frequency.value=420;g.gain.setValueAtTime(.0001,t);g.gain.exponentialRampToValueAtTime(.055,t+.06);g.gain.exponentialRampToValueAtTime(.0001,t+.78);o.connect(f);f.connect(g);g.connect(audioCtx.destination);o.start(t);o.stop(t+.82)}catch(e){}}
function showCouncilIntelligence(result,ctx,achievement,done){const el=$('#councilIntel'),text=$('#intelText'),ach=$('#intelAchievement'),btn=$('#intelContinue'),source=$('#intelSource');$('#intelSubject').textContent=`${ctx.player} // ${ctx.faction}`;text.textContent=result.text;const reason=String(result.reason||'uplink_failed').toUpperCase().replace(/_/g,' ');source.textContent=result.source==='llm'?'LIVE COGNITIVE LINK':`LOCAL CHAOS ENGINE // ${reason}`;if(achievement){ach.hidden=false;ach.innerHTML=`<div class="intel-ach-label">NEW ACHIEVEMENT</div><div class="intel-ach-title">${councilEscape(achievement.title)}</div><div class="intel-ach-copy">${councilEscape(achievement.copy)}</div>`}else{ach.hidden=true;ach.innerHTML=''}btn.textContent=ctx.pickNumber>=ctx.totalPlayers?'Reveal the Council Chamber →':'Summon Next Delegation →';btn.disabled=true;el.classList.remove('ready','leaving');el.classList.add('open');councilIntelSound();requestAnimationFrame(()=>requestAnimationFrame(()=>el.classList.add('ready')));const reduced=matchMedia('(prefers-reduced-motion: reduce)').matches;const unlock=setTimeout(()=>{btn.disabled=false;btn.focus({preventScroll:true})},reduced?100:900);btn.onclick=()=>{if(btn.disabled)return;clearTimeout(unlock);btn.disabled=true;el.classList.add('leaving');setTimeout(()=>{el.classList.remove('open','ready','leaving');done()},reduced?20:650)}}
