const COUNCIL_DOCKET_URL='https://dwngxrdmpbknjzzphkjd.supabase.co/functions/v1/galactic-council-docket';
function councilFormatDate(ts){if(!ts)return'Unknown date';try{return new Date(ts).toLocaleDateString(undefined,{year:'numeric',month:'short',day:'numeric'})}catch(e){return new Date(ts).toLocaleDateString()}}
function councilTopFaction(history){const entries=Object.entries(history.factions||{}).sort((a,b)=>b[1]-a[1]);return entries[0]?`${entries[0][0]} ×${entries[0][1]}`:'No pattern yet'}
function councilSessionResultText(session){if(session.status!=='complete')return'Result pending';return `${session.winnerName||councilProfileName(session.winnerId)}${session.winnerVp!=null?` • ${session.winnerVp} VP`:''}`}
function councilSessionRosterText(session){return(session.players||[]).map(p=>`${p.speaker?'✦ ':''}${p.name} — ${p.faction||'Faction pending'}`).join(' • ')}
function councilSessionBananaText(session,store=councilLoadStore()){
  if(session.status==='complete'&&typeof session.bananaAtStake==='boolean'){
    const before=session.bananaHolderBeforeId?councilProfileName(session.bananaHolderBeforeId):'Unassigned',after=session.bananaHolderAfterId?councilProfileName(session.bananaHolderAfterId):before;
    if(session.bananaAtStake)return session.winnerId===session.bananaHolderBeforeId?`🍌 BANANA DEFENDED • ${before} retains the Banana`:`🍌 BANANA TRANSFERRED • ${before} → ${after}`;
    return `🍌 NOT A BANANA GAME • ${before} was not seated`;
  }
  const preview=councilBananaPreviewForSession(session,store);
  if(!preview.holder)return'🍌 BANANA HOLDER NOT SET';
  return preview.atStake?`🍌 BANANA AT STAKE • ${preview.holder.displayName} is seated`:`🍌 BANANA SAFE • ${preview.holder.displayName} is not seated`;
}
function councilOpenBananaHolderForm(){
  const store=councilLoadStore(),holder=councilBananaHolder(store),profiles=[...(store.profiles||[])].sort((a,b)=>a.displayName.localeCompare(b.displayName)),body=$('#modalBody'),modal=$('#modal');if(!body||!modal)return;
  body.innerHTML=`<div class="modal-title">Golden Banana Holder</div><div class="modal-meta">Manual championship control</div><div class="record-help">Set the current Golden Banana holder. This establishes the Banana lineage from this point forward. A future game only puts the Banana at stake when the current holder is actually seated. If the holder is absent, the winner still gets a normal recorded win but the Banana does not move.</div><div class="record-form"><label><span>Current Holder</span><select id="bananaHolderSelect"><option value="">No holder / unassigned</option>${profiles.map(p=>`<option value="${p.id}" ${holder?.id===p.id?'selected':''}>${councilEscape(p.displayName)}</option>`).join('')}</select></label></div><div class="record-actions"><button class="btn" id="cancelBananaHolder">Cancel</button><button class="btn primary" id="saveBananaHolder">Save Banana Holder</button></div>`;
  modal.classList.add('open');$('#cancelBananaHolder').onclick=()=>modal.classList.remove('open');$('#saveBananaHolder').onclick=()=>{const id=$('#bananaHolderSelect').value,profile=councilSetBananaHolder(id||null);modal.classList.remove('open');toast(profile?`Golden Banana holder • ${profile.displayName}`:'Golden Banana holder cleared');councilRenderArchive()};
}

async function councilFetchDocketCases(limit=24){
  try{
    const controller=new AbortController(),timer=setTimeout(()=>controller.abort(),2200);
    const r=await fetch(COUNCIL_DOCKET_URL+'?limit='+encodeURIComponent(limit),{headers:{Accept:'application/json'},signal:controller.signal});clearTimeout(timer);
    if(!r.ok)return null;const data=await r.json();return Array.isArray(data?.cases)?data.cases:[];
  }catch(e){return null}
}
async function councilFetchDocketCase(caseNumber){
  try{
    const controller=new AbortController(),timer=setTimeout(()=>controller.abort(),2200);
    const r=await fetch(COUNCIL_DOCKET_URL+'?case='+encodeURIComponent(caseNumber),{headers:{Accept:'application/json'},signal:controller.signal});clearTimeout(timer);
    if(!r.ok)return null;const data=await r.json();return data?.case||null;
  }catch(e){return null}
}
function councilDocketDate(ts){return councilFormatDate(ts)}
function councilDocketDisposition(row){return String(row?.current_disposition||'ADVISORY').toUpperCase()}
async function councilOpenDocketCase(caseNumber){
  const body=$('#modalBody'),modal=$('#modal');if(!body||!modal)return;
  body.innerHTML='<div class="modal-title">Council Docket #'+String(caseNumber).padStart(3,'0')+'</div><div class="record-help">Retrieving the machine bureaucracy...</div>';modal.classList.add('open');
  const row=await councilFetchDocketCase(caseNumber);if(!row){body.innerHTML='<div class="modal-title">Docket Unavailable</div><div class="record-help">The Council misplaced the paperwork. This is somehow your problem.</div>';return}
  const filings=Array.isArray(row.filings)?row.filings:[];
  body.innerHTML=`<div class="modal-title">Council Docket #${String(row.case_number).padStart(3,'0')}</div><div class="modal-meta">${councilEscape(String(row.status||'ruled').toUpperCase())} • ${councilDocketDate(row.created_at)}${row.precedent?' • BINDING PRECEDENT':''}</div><div class="docket-case-parties"><b>${councilEscape(row.filer_name||'Unknown')}</b>${row.target_name?` <span>v.</span> <b>${councilEscape(row.target_name)}</b>`:''}</div><div class="record-help"><b>Original filing</b><br>${councilEscape(row.original_claim||'')}</div><div class="record-help"><b>Current ruling • ${councilEscape(councilDocketDisposition(row))}</b><br>${councilEscape(row.current_ruling||'No ruling text recorded.')}</div><div class="docket-filing-list">${filings.map((x,i)=>`<div class="docket-filing"><div><b>${i+1}. ${councilEscape(String(x.filing_type||'filing').toUpperCase())}</b><span>${councilDocketDate(x.created_at)} • ${councilEscape(String(x.disposition||'ADVISORY').toUpperCase())}${x.precedent?' • PRECEDENT':''}</span></div><p>${councilEscape(x.filing_text||'')}</p>${x.ruling_body?`<blockquote>${councilEscape(x.ruling_body)}</blockquote>`:''}</div>`).join('')||'<div class="archive-empty">No filings found. The bureaucracy has achieved enlightenment.</div>'}</div>`;
}
async function councilRenderDocket(){
  const list=$('#councilDocketList');if(!list)return;
  list.innerHTML='<div class="archive-empty">Retrieving Council case law...</div>';
  const rows=await councilFetchDocketCases(24);if(!list.isConnected)return;
  if(rows===null){list.innerHTML='<div class="archive-empty">Council Docket temporarily unavailable.</div>';return}
  if(!rows.length){list.innerHTML='<div class="archive-empty">No formal grievances have survived contact with the machine yet.</div>';return}
  list.innerHTML=rows.map(row=>`<article class="docket-card" data-docket-case="${row.case_number}"><div class="docket-top"><span>CASE #${String(row.case_number).padStart(3,'0')}</span><b>${councilEscape(councilDocketDisposition(row))}</b>${row.precedent?'<em>PRECEDENT</em>':''}</div><div class="docket-title">${councilEscape(row.title||'Untitled Procedural Disaster')}</div><div class="docket-parties">${councilEscape(row.filer_name||'Unknown')}${row.target_name?` v. ${councilEscape(row.target_name)}`:''}</div><div class="docket-claim">${councilEscape(row.original_claim||'')}</div><div class="docket-ruling">${councilEscape(row.current_ruling||'Ruling unavailable.')}</div><div class="docket-foot">${councilDocketDate(row.created_at)} • click for filings</div></article>`).join('');
  list.querySelectorAll('[data-docket-case]').forEach(card=>card.onclick=()=>councilOpenDocketCase(Number(card.dataset.docketCase)));
}

function councilRenderArchive(){
  const root=$('#councilArchive');if(!root)return;const store=councilLoadStore(),sessions=[...store.sessions].sort((a,b)=>(b.startedAt||0)-(a.startedAt||0)),completed=sessions.filter(s=>s.status==='complete'),profiles=[...store.profiles].sort((a,b)=>{const ha=councilHistoryFor(a.id),hb=councilHistoryFor(b.id);return hb.wins-ha.wins||hb.games-ha.games||hb.total-ha.total}),bananaHolder=councilBananaHolder(store);
  const wins=completed.length,unsealed=sessions.filter(s=>s.status!=='complete').length;
  root.innerHTML=`<div class="archive-hero"><div><div class="section-label">Council Intelligence // Long-Term Memory</div><div class="archive-title">Council Archives</div><div class="archive-copy">Recorded delegations, faction habits, victories, aliases, achievements, and the embarrassing evidence required for future commentary.</div></div><div class="archive-actions"><button class="btn primary" id="setBananaHolder">🍌 Set Banana Holder</button><button class="btn blue" id="clearTestRecords">Clear Test Records</button><button class="btn archive-danger" id="wipeCouncilMemory">Wipe All Memory</button></div></div>
  <div class="archive-metrics"><div><span>PLAYER PROFILES</span><b>${profiles.length}</b></div><div><span>COUNCIL SESSIONS</span><b>${sessions.length}</b></div><div><span>SEALED RESULTS</span><b>${wins}</b></div><div><span>AWAITING RESULT</span><b>${unsealed}</b></div><div><span>🍌 BANANA HOLDER</span><b>${councilEscape(bananaHolder?.displayName||'UNASSIGNED')}</b></div></div>
  <div class="archive-section-head"><div><div class="section-label">I • Delegation Dossiers</div><h3>Player Profiles</h3></div><span>Aliases let multiple names point to the same Council identity.</span></div>
  <div class="profile-grid">${profiles.length?profiles.map(p=>{const h=councilHistoryFor(p.id),ach=h.achievements||[],aliases=(p.aliases||[]).filter(a=>councilNormalizeName(a)!==councilNormalizeName(p.displayName));return `<article class="profile-card"><div class="profile-head"><div class="profile-monogram">${councilEscape(p.displayName.slice(0,2).toUpperCase())}</div><div><div class="profile-name">${councilEscape(p.displayName)}</div><div class="profile-aliases">${aliases.length?`Also known as ${aliases.map(councilEscape).join(', ')}`:'Primary designation only'}</div></div></div><div class="profile-stats"><div><b>${h.games}</b><span>Games</span></div><div><b>${h.wins}</b><span>Wins</span></div><div><b>${h.games?h.winRate+'%':'—'}</b><span>Win Rate</span></div><div><b>${h.speakerCount}</b><span>Speaker</span></div></div><div class="profile-detail"><span>Most repeated faction</span><b>${councilEscape(councilTopFaction(h))}</b></div>${h.holdsBanana?`<div class="profile-streak">🍌 CURRENT GOLDEN BANANA HOLDER</div>`:''}${h.winStreak?`<div class="profile-streak">PERSONAL WIN STREAK // ${h.winStreak}</div>`:''}${h.lastGame?`<div class="profile-last">Last recorded game: <b>${councilEscape(h.lastGame.faction||'Unknown faction')}</b> • ${h.lastGame.won?'VICTORY':'Defeat'}${h.lastGame.vp!=null?` • ${h.lastGame.vp} VP`:''}</div>`:''}${ach.length?`<div class="profile-achievements">${ach.slice(-4).map(a=>`<span title="${councilEscape(a.copy||'')}">${councilEscape(a.title)}</span>`).join('')}</div>`:''}<button class="profile-alias-btn" data-alias-profile="${p.id}">+ Add / Merge Alias</button></article>`}).join(''):'<div class="archive-empty">No permanent player dossiers yet. Convene a Council and the surveillance begins.</div>'}</div>
  <div class="archive-section-head sessions-head"><div><div class="section-label">II • Historical Record</div><h3>Council Sessions</h3></div><span>Seal the winner after the game. Unfinished records stay here until you do.</span></div>
  <div class="session-list">${sessions.length?sessions.map(s=>`<article class="session-card ${s.status==='complete'?'sealed':'pending'}"><div class="session-top"><div><span>${councilFormatDate(s.startedAt)}</span><b>${s.status==='complete'?'COUNCIL RECORD SEALED':'RESULT PENDING'}</b></div><div class="session-actions"><button class="btn ${s.status==='complete'?'blue':'primary'}" data-edit-session="${s.id}">${s.status==='complete'?'Edit Result':'Seal Result'}</button><button class="btn archive-danger" data-delete-session="${s.id}">Delete</button></div></div><div class="session-result">${councilEscape(councilSessionResultText(s))}</div><div class="session-roster">${councilEscape(councilSessionRosterText(s))}</div><div class="session-meta">${councilEscape(councilSessionBananaText(s,store))}</div>${s.note?`<div class="session-note">“${councilEscape(s.note)}”</div>`:''}<div class="session-meta">Seed ${councilEscape(s.seed||'unknown')} • ${(s.expansions||[]).map(id=>councilEscape(E[id]?.short||id)).join(' / ')}</div></article>`).join(''):'<div class="archive-empty">No Council Sessions have been recorded yet.</div>'}</div>
  <div class="archive-section-head sessions-head"><div><div class="section-label">III • Council Docket</div><h3>Grievances & Case Law</h3></div><span>Formal complaints, appeals, motions, machine rulings, and the occasional regrettable precedent.</span></div>
  <div class="docket-toolbar"><span>Allegations remain allegations unless separately established as table lore.</span><button class="btn blue" id="refreshCouncilDocket">Refresh Docket</button></div>
  <div class="docket-list" id="councilDocketList"><div class="archive-empty">Retrieving Council case law...</div></div>`;
  $('#setBananaHolder').onclick=()=>councilOpenBananaHolderForm();
  $('#refreshCouncilDocket').onclick=()=>councilRenderDocket();
  councilRenderDocket();
  $('#clearTestRecords').onclick=()=>{if(!confirm('Remove profiles named Test/Test1/Test2 and any sessions containing them? Real player records are left alone.'))return;const n=councilClearTestRecords();toast(n?`Purged ${n} test profile${n===1?'':'s'}`:'No test profiles found');councilRenderArchive()};
  $('#wipeCouncilMemory').onclick=()=>{if(!confirm('Wipe ALL Council player profiles, sessions, achievements, and draft history from this browser? This cannot be undone.'))return;if(!confirm('Final warning: erase the entire Council Archive?'))return;councilWipeAllMemory();toast('Council memory erased');councilRenderArchive()};
  root.querySelectorAll('[data-alias-profile]').forEach(btn=>btn.onclick=()=>{const p=store.profiles.find(x=>x.id===btn.dataset.aliasProfile);if(!p)return;const alias=prompt(`Add another name for ${p.displayName}. If that name already has a profile, the records will be merged.`);if(!alias)return;if(councilAddAlias(p.id,alias)){toast(`${alias} now resolves to ${p.displayName}`);councilRenderArchive()}});
  root.querySelectorAll('[data-edit-session]').forEach(btn=>btn.onclick=()=>councilOpenSessionForm(btn.dataset.editSession));
  root.querySelectorAll('[data-delete-session]').forEach(btn=>btn.onclick=()=>{const live=councilLoadStore(),session=live.sessions.find(s=>s.id===btn.dataset.deleteSession);if(!session)return;const label=session.status==='complete'?'sealed session':'pending session';if(!confirm(`Delete this ${label}?\n\nThis removes the session, its recorded draft picks, its result, and achievements tied directly to it. Player dossiers remain.`))return;const removed=councilDeleteSession(session.id);if(!removed)return;toast('Council session deleted');councilRenderArchive()});
}
function councilOpenSessionForm(sessionId){
  const store=councilLoadStore(),session=store.sessions.find(s=>s.id===sessionId);if(!session)return;const body=$('#modalBody'),modal=$('#modal');
  const bananaText=councilSessionBananaText(session,store);
  body.innerHTML=`<div class="modal-title">${session.status==='complete'?'Edit Council Result':'Close Council Session'}</div><div class="modal-meta">${councilFormatDate(session.startedAt)} • ${councilEscape(session.seed||'')}</div><div class="record-help">Tell the Council what actually happened. Winner is required; VP and one lore note are optional.</div><div class="record-help"><b>${councilEscape(bananaText)}</b><br><small>The Golden Banana only transfers when the current holder is seated in this game.</small></div><div class="record-form"><label><span>Winner</span><select id="recordWinner"><option value="">Select the victorious degenerate</option>${(session.players||[]).map(p=>`<option value="${p.profileId}" ${session.winnerId===p.profileId?'selected':''}>${councilEscape(p.name)}${p.faction?` — ${councilEscape(p.faction)}`:''}</option>`).join('')}</select></label><label><span>Victory Points <small>optional</small></span><input id="recordVp" type="number" min="0" max="30" step="1" value="${session.winnerVp??''}" placeholder="10"></label><label class="record-note"><span>Council Lore Note <small>optional</small></span><textarea id="recordNote" maxlength="500" placeholder="Chris betrayed Shane on Mecatol and immediately died.">${councilEscape(session.note||'')}</textarea></label></div><div class="record-roster">${(session.players||[]).map(p=>`<div><b>${p.speaker?'✦ ':''}${councilEscape(p.name)}</b><span>${councilEscape(p.faction||'Faction not recorded')}</span></div>`).join('')}</div><div class="record-actions"><button class="btn" id="cancelRecord">Cancel</button><button class="btn primary" id="sealRecord">Seal Council Record</button></div>`;
  modal.classList.add('open');$('#cancelRecord').onclick=()=>modal.classList.remove('open');$('#sealRecord').onclick=()=>{const winnerId=$('#recordWinner').value;if(!winnerId){toast('Choose the winner before sealing the record');return}const vp=$('#recordVp').value,note=$('#recordNote').value,result=councilCompleteSession(session.id,{winnerId,vp,note});if(!result){toast('Council record could not be sealed');return}modal.classList.remove('open');toast(`Record sealed • ${result.winnerName} wins`);if(state.phase==='final'&&state.councilSessionId===session.id)councilDecorateFinal();if($('#historyView')?.classList.contains('active'))councilRenderArchive()};
}
function councilDecorateFinal(){
  councilUpdateSessionRoster();const store=councilLoadStore(),session=councilCurrentSession(store),stage=$('#stageScreen');if(!session||!stage)return;stage.querySelector('.session-final-status')?.remove();stage.querySelector('#sessionCloseBtn')?.remove();const actions=stage.querySelector('.stage-actions');if(!actions)return;
  const status=document.createElement('div');status.className=`session-final-status ${session.status==='complete'?'sealed':'pending'}`;status.innerHTML=session.status==='complete'?`<span>COUNCIL RECORD SEALED</span><b>${councilEscape(session.winnerName||'Winner recorded')}${session.winnerVp!=null?` • ${session.winnerVp} VP`:''}</b>`:`<span>LONG-TERM MEMORY</span><b>Draft saved • game result still pending</b>`;actions.parentNode.insertBefore(status,actions);
  const btn=document.createElement('button');btn.className=`btn ${session.status==='complete'?'blue':'primary'}`;btn.id='sessionCloseBtn';btn.textContent=session.status==='complete'?'Edit Council Record':'Close Council Session';btn.onclick=()=>councilOpenSessionForm(session.id);actions.insertBefore(btn,actions.querySelector('#newDraft'));
}
const councilBaseBegin=begin;begin=function(){councilBaseBegin();if(state.phase==='order'&&state.assignments.length)councilStartSession()};
const councilBaseRenderFinal=renderFinal;renderFinal=function(){councilBaseRenderFinal();councilDecorateFinal()};
const councilBaseSwitchView=switchView;switchView=function(id){councilBaseSwitchView(id);if(id==='history')councilRenderArchive()};
