function councilFormatDate(ts){if(!ts)return'Unknown date';try{return new Date(ts).toLocaleDateString(undefined,{year:'numeric',month:'short',day:'numeric'})}catch(e){return new Date(ts).toLocaleDateString()}}
function councilTopFaction(history){const entries=Object.entries(history.factions||{}).sort((a,b)=>b[1]-a[1]);return entries[0]?`${entries[0][0]} ×${entries[0][1]}`:'No pattern yet'}
function councilSessionResultText(session){if(session.status!=='complete')return'Result pending';return `${session.winnerName||councilProfileName(session.winnerId)}${session.winnerVp!=null?` • ${session.winnerVp} VP`:''}`}
function councilSessionRosterText(session){return(session.players||[]).map(p=>`${p.speaker?'✦ ':''}${p.name} — ${p.faction||'Faction pending'}`).join(' • ')}
function councilRenderArchive(){
  const root=$('#councilArchive');if(!root)return;const store=councilLoadStore(),sessions=[...store.sessions].sort((a,b)=>(b.startedAt||0)-(a.startedAt||0)),completed=sessions.filter(s=>s.status==='complete'),profiles=[...store.profiles].sort((a,b)=>{const ha=councilHistoryFor(a.id),hb=councilHistoryFor(b.id);return hb.wins-ha.wins||hb.games-ha.games||hb.total-ha.total});
  const wins=completed.length,unsealed=sessions.filter(s=>s.status!=='complete').length;
  root.innerHTML=`<div class="archive-hero"><div><div class="section-label">Council Intelligence // Long-Term Memory</div><div class="archive-title">Council Archives</div><div class="archive-copy">Recorded delegations, faction habits, victories, aliases, achievements, and the embarrassing evidence required for future commentary.</div></div><div class="archive-actions"><button class="btn blue" id="clearTestRecords">Clear Test Records</button><button class="btn archive-danger" id="wipeCouncilMemory">Wipe All Memory</button></div></div>
  <div class="archive-metrics"><div><span>PLAYER PROFILES</span><b>${profiles.length}</b></div><div><span>COUNCIL SESSIONS</span><b>${sessions.length}</b></div><div><span>SEALED RESULTS</span><b>${wins}</b></div><div><span>AWAITING RESULT</span><b>${unsealed}</b></div></div>
  <div class="archive-section-head"><div><div class="section-label">I • Delegation Dossiers</div><h3>Player Profiles</h3></div><span>Aliases let multiple names point to the same Council identity.</span></div>
  <div class="profile-grid">${profiles.length?profiles.map(p=>{const h=councilHistoryFor(p.id),ach=h.achievements||[],aliases=(p.aliases||[]).filter(a=>councilNormalizeName(a)!==councilNormalizeName(p.displayName));return `<article class="profile-card"><div class="profile-head"><div class="profile-monogram">${councilEscape(p.displayName.slice(0,2).toUpperCase())}</div><div><div class="profile-name">${councilEscape(p.displayName)}</div><div class="profile-aliases">${aliases.length?`Also known as ${aliases.map(councilEscape).join(', ')}`:'Primary designation only'}</div></div></div><div class="profile-stats"><div><b>${h.games}</b><span>Games</span></div><div><b>${h.wins}</b><span>Wins</span></div><div><b>${h.games?h.winRate+'%':'—'}</b><span>Win Rate</span></div><div><b>${h.speakerCount}</b><span>Speaker</span></div></div><div class="profile-detail"><span>Most repeated faction</span><b>${councilEscape(councilTopFaction(h))}</b></div>${h.winStreak?`<div class="profile-streak">CURRENT WIN STREAK // ${h.winStreak}</div>`:''}${h.lastGame?`<div class="profile-last">Last recorded game: <b>${councilEscape(h.lastGame.faction||'Unknown faction')}</b> • ${h.lastGame.won?'VICTORY':'Defeat'}${h.lastGame.vp!=null?` • ${h.lastGame.vp} VP`:''}</div>`:''}${ach.length?`<div class="profile-achievements">${ach.slice(-4).map(a=>`<span title="${councilEscape(a.copy||'')}">${councilEscape(a.title)}</span>`).join('')}</div>`:''}<button class="profile-alias-btn" data-alias-profile="${p.id}">+ Add / Merge Alias</button></article>`}).join(''):'<div class="archive-empty">No permanent player dossiers yet. Convene a Council and the surveillance begins.</div>'}</div>
  <div class="archive-section-head sessions-head"><div><div class="section-label">II • Historical Record</div><h3>Council Sessions</h3></div><span>Seal the winner after the game. Unfinished records stay here until you do.</span></div>
  <div class="session-list">${sessions.length?sessions.map(s=>`<article class="session-card ${s.status==='complete'?'sealed':'pending'}"><div class="session-top"><div><span>${councilFormatDate(s.startedAt)}</span><b>${s.status==='complete'?'COUNCIL RECORD SEALED':'RESULT PENDING'}</b></div><button class="btn ${s.status==='complete'?'blue':'primary'}" data-edit-session="${s.id}">${s.status==='complete'?'Edit Result':'Seal Result'}</button></div><div class="session-result">${councilEscape(councilSessionResultText(s))}</div><div class="session-roster">${councilEscape(councilSessionRosterText(s))}</div>${s.note?`<div class="session-note">“${councilEscape(s.note)}”</div>`:''}<div class="session-meta">Seed ${councilEscape(s.seed||'unknown')} • ${(s.expansions||[]).map(id=>councilEscape(E[id]?.short||id)).join(' / ')}</div></article>`).join(''):'<div class="archive-empty">No Council Sessions have been recorded yet.</div>'}</div>`;
  $('#clearTestRecords').onclick=()=>{if(!confirm('Remove profiles named Test/Test1/Test2 and any sessions containing them? Real player records are left alone.'))return;const n=councilClearTestRecords();toast(n?`Purged ${n} test profile${n===1?'':'s'}`:'No test profiles found');councilRenderArchive()};
  $('#wipeCouncilMemory').onclick=()=>{if(!confirm('Wipe ALL Council player profiles, sessions, achievements, and draft history from this browser? This cannot be undone.'))return;if(!confirm('Final warning: erase the entire Council Archive?'))return;councilWipeAllMemory();toast('Council memory erased');councilRenderArchive()};
  root.querySelectorAll('[data-alias-profile]').forEach(btn=>btn.onclick=()=>{const p=store.profiles.find(x=>x.id===btn.dataset.aliasProfile);if(!p)return;const alias=prompt(`Add another name for ${p.displayName}. If that name already has a profile, the records will be merged.`);if(!alias)return;if(councilAddAlias(p.id,alias)){toast(`${alias} now resolves to ${p.displayName}`);councilRenderArchive()}});
  root.querySelectorAll('[data-edit-session]').forEach(btn=>btn.onclick=()=>councilOpenSessionForm(btn.dataset.editSession));
}
function councilOpenSessionForm(sessionId){
  const store=councilLoadStore(),session=store.sessions.find(s=>s.id===sessionId);if(!session)return;const body=$('#modalBody'),modal=$('#modal');
  body.innerHTML=`<div class="modal-title">Close Council Session</div><div class="modal-meta">${councilFormatDate(session.startedAt)} • ${councilEscape(session.seed||'')}</div><div class="record-help">Tell the Council what actually happened. Winner is required; VP and one lore note are optional.</div><div class="record-form"><label><span>Winner</span><select id="recordWinner"><option value="">Select the victorious degenerate</option>${(session.players||[]).map(p=>`<option value="${p.profileId}" ${session.winnerId===p.profileId?'selected':''}>${councilEscape(p.name)}${p.faction?` — ${councilEscape(p.faction)}`:''}</option>`).join('')}</select></label><label><span>Victory Points <small>optional</small></span><input id="recordVp" type="number" min="0" max="30" step="1" value="${session.winnerVp??''}" placeholder="10"></label><label class="record-note"><span>Council Lore Note <small>optional</small></span><textarea id="recordNote" maxlength="500" placeholder="Chris betrayed Shane on Mecatol and immediately died.">${councilEscape(session.note||'')}</textarea></label></div><div class="record-roster">${(session.players||[]).map(p=>`<div><b>${p.speaker?'✦ ':''}${councilEscape(p.name)}</b><span>${councilEscape(p.faction||'Faction not recorded')}</span></div>`).join('')}</div><div class="record-actions"><button class="btn" id="cancelRecord">Cancel</button><button class="btn primary" id="sealRecord">Seal Council Record</button></div>`;
  modal.classList.add('open');$('#cancelRecord').onclick=()=>modal.classList.remove('open');$('#sealRecord').onclick=()=>{const winnerId=$('#recordWinner').value;if(!winnerId){toast('Choose the winner before sealing the record');return}const vp=$('#recordVp').value,note=$('#recordNote').value,result=councilCompleteSession(session.id,{winnerId,vp,note});if(!result){toast('Council record could not be sealed');return}modal.classList.remove('open');toast(`Record sealed • ${result.winnerName} wins`);if(state.phase==='final'&&state.councilSessionId===session.id)councilDecorateFinal();if($('#historyView')?.classList.contains('active'))councilRenderArchive()};
}
function councilDecorateFinal(){
  councilUpdateSessionRoster();const store=councilLoadStore(),session=councilCurrentSession(store),stage=$('#stageScreen');if(!session||!stage)return;stage.querySelector('.session-final-status')?.remove();stage.querySelector('#sessionCloseBtn')?.remove();const actions=stage.querySelector('.stage-actions');if(!actions)return;
  const status=document.createElement('div');status.className=`session-final-status ${session.status==='complete'?'sealed':'pending'}`;status.innerHTML=session.status==='complete'?`<span>COUNCIL RECORD SEALED</span><b>${councilEscape(session.winnerName||'Winner recorded')}${session.winnerVp!=null?` • ${session.winnerVp} VP`:''}</b>`:`<span>LONG-TERM MEMORY</span><b>Draft saved • game result still pending</b>`;actions.parentNode.insertBefore(status,actions);
  const btn=document.createElement('button');btn.className=`btn ${session.status==='complete'?'blue':'primary'}`;btn.id='sessionCloseBtn';btn.textContent=session.status==='complete'?'Edit Council Record':'Close Council Session';btn.onclick=()=>councilOpenSessionForm(session.id);actions.insertBefore(btn,actions.querySelector('#newDraft'));
}
const councilBaseBegin=begin;begin=function(){councilBaseBegin();if(state.phase==='order'&&state.assignments.length)councilStartSession()};
const councilBaseRenderFinal=renderFinal;renderFinal=function(){councilBaseRenderFinal();councilDecorateFinal()};
const councilBaseSwitchView=switchView;switchView=function(id){councilBaseSwitchView(id);if(id==='history')councilRenderArchive()};
