const ART_ROOT='https://raw.githubusercontent.com/paxmagnifica/ti4-companion/main/client/public/factionCheatsheets/';
const artFiles={
  'The Arborec':'the_arborec.png','The Barony of Letnev':'the_barony_of_letnev.png','The Clan of Saar':'the_clan_of_saar.png','The Embers of Muaat':'the_embers_of_muaat.png','The Emirates of Hacan':'the_emirates_of_hacan.png','The Federation of Sol':'the_federation_of_sol.png','The Ghosts of Creuss':'the_ghosts_of_creuss.png','The L1Z1X Mindnet':'the_l1z1x_mindnet.png','The Mentak Coalition':'the_mentak_coalition.png','The Naalu Collective':'the_naalu_collective.png','The Nekro Virus':'the_nekro_virus.png',"Sardakk N'orr":'sardakk_norr.png','The Universities of Jol-Nar':'the_universities_of_jol__nar.png','The Winnu':'the_winnu.png','The Xxcha Kingdom':'the_xxcha_kingdom.png','The Yin Brotherhood':'the_yin_brotherhood.png','The Yssaril Tribes':'the_yssaril_tribes.png','The Argent Flight':'the_argent_flight.png','The Empyrean':'the_empyrean.png','The Mahact Gene-Sorcerers':'the_mahact_gene__sorcerers.png','The Naaz-Rokha Alliance':'the_naaz__rokha_alliance.png','The Nomad':'the_nomad.png','The Titans of Ul':'the_titans_of_ul.png',"The Vuil'raith Cabal":'the_vuilraith_cabal.png'
};
const E={base:{name:'Base Game',short:'BASE',color:'#a88738'},pok:{name:'Prophecy of Kings',short:'PoK',color:'#6c68cf'},codex3:{name:'Codex III',short:'CX3',color:'#4a9daf'},te:{name:"Thunder's Edge",short:'TE',color:'#d96a3d'},ds:{name:'Discordant Stars',short:'DS',color:'#a65fb6'}};
const data={
base:[
 ['The Arborec','#70a34b','Military','A living war machine that grows armies from the planets it controls.'],['The Barony of Letnev','#6e6d8c','Military','Heavy fleets, huge capacity and the subtle diplomatic art of bringing more dreadnoughts.'],['The Clan of Saar','#d4854b','High Skill','Nomadic production and terrifying mobility. Your home is wherever your fleet happens to be.'],['The Embers of Muaat','#e34d45','Military','Start with a War Sun and spend the game reminding everyone that you started with a War Sun.'],['The Emirates of Hacan','#d9b238','Economic','Trade with everyone, profit from everyone, and weaponize an absurd pile of trade goods.'],['The Federation of Sol','#4b9bd1','Beginner','Flexible, forgiving and excellent at putting infantry exactly where they need to be.'],['The Ghosts of Creuss','#65c8e7','High Skill','Wormhole sorcery turns the map into a suggestion. Strike from impossible angles.'],['The L1Z1X Mindnet','#8770d6','Military','Premium dreadnought violence backed by production theft and relentless pressure.'],['The Mentak Coalition','#d56a43','High Skill','Pirates, ambushes and taxes. Every neighbour suddenly develops trust issues.'],['The Naalu Collective','#76a46b','Political','Initiative control, fighter swarms and the unnerving ability to move before everyone else.'],['The Nekro Virus','#a050a4','High Skill','No traditional research. Steal the galaxy’s best technology by fighting for it.'],["Sardakk N'orr",'#a27552','Military','Combat bonuses, terrifying bugs and the belief that technology is optional.'],['The Universities of Jol-Nar','#5574c9','Tech','Research everything. Then research the thing that lets you research more things.'],['The Winnu','#bf659d','Political','Mecatol specialists who become terrifying once the throne room is theirs.'],['The Xxcha Kingdom','#68ac72','Political','Diplomacy backed by cannons. Smile politely while making the agenda phase yours.'],['The Yin Brotherhood','#d0af6b','High Skill','Explosive devotion, ground combat tricks and one extremely persuasive flagship.'],['The Yssaril Tribes','#5e9861','High Skill','Action-card hoarders with information, stalls and exactly the answer nobody wanted you to have.']],
pok:[
 ['The Argent Flight','#efbd39','Military','Fast destroyers, sharp tempo and excellent control over crowded space.'],['The Empyrean','#7452bd','Political','Explore the dark, sell access and turn empty space into political leverage.'],['The Mahact Gene-Sorcerers','#b19456','High Skill','Steal command tokens, borrow commanders and make the whole table slightly nervous.'],['The Naaz-Rokha Alliance','#82984f','Economic','Explore aggressively, upgrade relics and deploy some of the nastiest mechs in the galaxy.'],['The Nomad','#4776bd','Beginner','A premium flagship, flexible economy and a toolbox built for opportunistic scoring.'],['The Titans of Ul','#929292','Economic','Awaken ancient cruisers, fortify planets and turn infrastructure into momentum.'],["The Vuil'raith Cabal",'#b43a42','Military','Capture destroyed units, build for free and use dimensional tears like predatory toll booths.']],
codex3:[['The Council Keleres','#5e91b6','Political','Galactic law enforcement with flexible setup and a talent for surviving the centre.']],
te:[
 ['Last Bastion','#699fd0','Beginner','Resilient defenders that turn liberation and sacrifice into momentum.'],['The Deepwrought Scholarate','#7597c6','Tech','Oceanic scholars who can coexist, bargain and build a strange technology engine.'],['The Crimson Rebellion','#d64747','High Skill','Rift-touched rebels who drag enemies into brutal, asymmetric confrontations.'],['The Ral Nel Consortium','#d4913e','Economic','Commerce specialists who want the entire galaxy trading through their network.'],['The Firmament','#8172bd','High Skill','A transforming faction that rewards planning for a dramatic midgame identity shift.']],
ds:[
 ['The Augurs of Illusoria','#b997d5','Community','Discordant Stars faction.'],['The Celdauri Trade Confederation','#d5aa3d','Community','Discordant Stars faction.'],['The Cheiran Hordes','#a45e3c','Community','Discordant Stars faction.'],['The Dih-Mohn Flotilla','#5fa4c1','Community','Discordant Stars faction.'],['The Edyn Mandate','#88ad62','Community','Discordant Stars faction.'],['The Florzen Profiteer','#cf8a45','Community','Discordant Stars faction.'],['The Free Systems Compact','#5b8dc9','Community','Discordant Stars faction.'],['The Ghemina Raiders','#ad6d6d','Community','Discordant Stars faction.'],['The Ghoti Wayfarers','#4baf9f','Community','Discordant Stars faction.'],['The Gledge Union','#9b8b6c','Community','Discordant Stars faction.'],['The Glimmer of Mortheus','#8c61ae','Community','Discordant Stars faction.'],['The Kollecc Society','#c87b48','Community','Discordant Stars faction.'],['The Kortali Tribunal','#6175b5','Community','Discordant Stars faction.'],['The Kyro Sodality','#78ad72','Community','Discordant Stars faction.'],['The Lanefir Remnants','#bb788a','Community','Discordant Stars faction.'],['The Li-Zho Dynasty','#d79a4b','Community','Discordant Stars faction.'],["The L'tokk Khrask",'#689a60','Community','Discordant Stars faction.'],['The Mirveda Protectorate','#6f8fc3','Community','Discordant Stars faction.'],['The Monks of Kolume','#aa986c','Community','Discordant Stars faction.'],['The Myko-Mentari','#78a67c','Community','Discordant Stars faction.'],['The Nivyn Star Kings','#9677b8','Community','Discordant Stars faction.'],['The Nokar Salvagers','#988b78','Community','Discordant Stars faction.'],['The Olradin League','#c6ab5c','Community','Discordant Stars faction.'],["The Roh'Dhna Mecatol",'#775aa6','Community','Discordant Stars faction.'],['The Savages of Cymiae','#b66b59','Community','Discordant Stars faction.'],['The Shipwrights of Axis','#5d7fb0','Community','Discordant Stars faction.'],['The Zelian Purifier','#c85a4d','Community','Discordant Stars faction.']]
};
const factions=[];Object.entries(data).forEach(([exp,rows])=>rows.forEach((r,i)=>factions.push({name:r[0],color:r[1],tag:r[2],blurb:r[3],exp,id:exp+'-'+i,art:artFiles[r[0]]?ART_ROOT+artFiles[r[0]]:null})));
