function validateStart(){const available=expFactions().length,need=state.players*state.perPlayer;if(need>available){toast(`Need ${need} factions • only ${available} enabled`);return false}return true}
function begin(){if(!validateStart())return;saveNames();state.phase='order';state.current=0;state.picks=[];state.assignments=[];state.selected=null;const rng=rngFrom(state.seed);state.speakerOrder=shuffle(Array.from({length:state.players},(_,i)=>i),rng);const pool=shuffle(expFactions(),rng);state.assignments=state.speakerOrder.map((playerIdx,pos)=>({playerIdx,pos,options:pool.slice(pos*state.perPlayer,(pos+1)*state.perPlayer),chosen:null}));$('#setupScreen').hidden=true;$('#stageScreen').hidden=false;if(state.mode==='random'){state.deal=state.assignments.map(a=>({playerIdx:a.playerIdx,pos:a.pos,options:a.options}));renderRandomDeal()}else renderSpeakerReveal();playImpact()}
function renderSpeakerReveal(){state.phase='order';const s=$('#stageScreen');s.innerHTML=`<div class="stage-head"><div class="stage-kicker">The Speaker Token Has Chosen</div><div class="stage-title">Council Order</div><div class="stage-sub">This order also determines faction pick priority.</div></div><div class="order-grid">${state.assignments.map((a,i)=>`<div class="order-card" style="animation-delay:${i*.08}s"><div class="order-num">${i+1}</div><div class="order-name">${playerName(a.playerIdx)}</div>${i===0?'<div class="speaker-tag">✦ Speaker</div>':'<div class="speaker-tag" style="color:var(--muted)">Pick '+(i+1)+'</div>'}</div>`).join('')}</div><div class="stage-actions"><button class="btn" id="backConfig">← Configuration</button><button class="btn primary" id="beginPicks">⬡ Begin Faction Selections ⬡</button></div>`;$('#beginPicks').onclick=()=>{state.phase='pick';renderPick()};$('#backConfig').onclick=resetSetup}
function renderPick(){state.phase='pick';const a=state.assignments[state.current];if(!a){renderFinal();return}const chosen=new Set(state.picks.map(p=>p.faction.name));const pct=(state.current/state.players)*100;$('#stageScreen').innerHTML=`<div class="pick-banner"><div><div class="who">${playerName(a.playerIdx)} — choose your civilization</div><div class="meta">Pick ${state.current+1} of ${state.players}${state.current===0?' • Speaker':''}</div></div><div><div class="progress"><i style="width:${pct}%"></i></div><div style="text-align:right;font-size:10px;color:var(--muted);margin-top:5px">${state.current}/${state.players} locked</div></div></div><div class="faction-grid">${a.options.map(f=>factionCard(f,{selected:state.selected===f.name,locked:chosen.has(f.name)})).join('')}</div><div class="stage-actions"><button class="btn" id="undoBtn" ${state.picks.length?'':'disabled'}>↶ Undo Last Pick</button><button class="btn blue" id="archiveBtn">Faction Archive</button><button class="btn primary" id="confirmBtn" ${state.selected?'':'disabled'}>Confirm Selection</button></div>`;$('#confirmBtn').onclick=confirmSelection;$('#undoBtn').onclick=undoPick;$('#archiveBtn').onclick=()=>switchView('guide')}
function selectFaction(name){state.selected=name;renderPick()}
function confirmSelection(){if(!state.selected)return;const a=state.assignments[state.current],f=a.options.find(x=>x.name===state.selected);if(!f)return;showCeremony(playerName(a.playerIdx),f,()=>{a.chosen=f;state.picks.push({playerIdx:a.playerIdx,pos:a.pos,faction:f});state.current++;state.selected=null;if(state.current>=state.players)renderFinal();else renderPick()})}
function undoPick(){if(!state.picks.length)return;state.picks.pop();state.current=Math.max(0,state.current-1);state.assignments[state.current].chosen=null;state.selected=null;renderPick();toast('Last pick returned to the void')}
function showCeremony(player,f,done){const c=$('#ceremony');$('#ceremonyPlayer').textContent=player;$('#ceremonyName').textContent=f.name;const sig=$('#ceremonySigil');sig.style.setProperty('--accent',f.color);sig.innerHTML=f.art?`<img src="${f.art}" alt="" onerror="this.outerHTML='<span>${initials(f.name)}</span>'">`:`<span>${initials(f.name)}</span>`;c.classList.add('open');playImpact();setTimeout(()=>{c.classList.remove('open');done()},matchMedia('(prefers-reduced-motion: reduce)').matches?150:1350)}
function rosterHtml(){return state.picks.map(p=>{const f=p.faction;return `<div class="roster-card" style="--accent:${f.color}"><div class="roster-sigil">${f.art?`<img src="${f.art}" alt="" onerror="this.outerHTML='${initials(f.name)}'">`:initials(f.name)}</div><div><div class="roster-player">${p.pos===0?'✦ ':''}${playerName(p.playerIdx)}${p.pos===0?'<span class="crown">SPEAKER</span>':''}</div><div class="roster-faction">${f.name}</div><div class="roster-meta">Pick ${p.pos+1} • ${E[f.exp].short} • ${f.tag}</div></div></div>`}).join('')}
function renderFinal(){state.phase='final';$('#stageScreen').innerHTML=`<div class="stage-head"><div class="stage-kicker">The Galaxy Has Witnessed</div><div class="stage-title">The Council Chamber</div><div class="stage-sub">Factions locked. Speaker crowned. Grudges may now begin.</div></div><div class="roster">${rosterHtml()}</div><div class="stage-actions"><button class="btn" id="undoFinal">↶ Undo Last Pick</button><button class="btn blue" id="copyRoster">⧉ Copy Roster</button><button class="btn blue" id="copyLinkFinal">⧉ Copy Draft Link</button><button class="btn primary" id="newDraft">New Draft</button></div>`;$('#undoFinal').onclick=()=>{if(state.picks.length){state.picks.pop();state.current=state.players-1;state.assignments[state.current].chosen=null;state.selected=null;renderPick()}};$('#copyRoster').onclick=()=>copyText(rosterText(),'Council roster copied');$('#copyLinkFinal').onclick=()=>copyText(draftUrl(),'Draft link copied');$('#newDraft').onclick=()=>{setSeed(newSeed());resetSetup()};playImpact()}
function rosterText(){return ['TI4 GALACTIC COUNCIL',`Seed: ${state.seed}`,'',...state.picks.map(p=>`${p.pos+1}. ${playerName(p.playerIdx)} — ${p.faction.name}${p.pos===0?' (SPEAKER)':''}`)].join('\n')}
function renderRandomDeal(){state.phase='random';$('#stageScreen').innerHTML=`<div class="stage-head"><div class="stage-kicker">The Galaxy Has Spoken</div><div class="stage-title">Faction Deal</div><div class="stage-sub">Each delegation receives ${state.perPlayer} option${state.perPlayer===1?'':'s'}. The first delegation holds the speaker token.</div></div>${state.deal.map(d=>`<div class="deal-player"><h3>${d.pos===0?'✦ ':''}${playerName(d.playerIdx)}${d.pos===0?' — SPEAKER':''}</h3><div class="deal-grid">${d.options.map(f=>`<div class="deal-mini" style="--accent:${f.color}"><b>${f.name}</b><small>${E[f.exp].short} • ${f.tag}</small></div>`).join('')}</div></div>`).join('')}<div class="stage-actions"><button class="btn blue" id="copyDeal">⧉ Copy Deal</button><button class="btn" id="redeal">↻ Redraft</button><button class="btn primary" id="newRandom">New Setup</button></div>`;$('#copyDeal').onclick=()=>copyText(randomText(),'Faction deal copied');$('#redeal').onclick=()=>{setSeed(newSeed());begin()};$('#newRandom').onclick=resetSetup}
function randomText(){return ['TI4 RANDOM FACTION DEAL',`Seed: ${state.seed}`,'',...state.deal.map(d=>`${d.pos+1}. ${playerName(d.playerIdx)}${d.pos===0?' (SPEAKER)':''}: ${d.options.map(f=>f.name).join(' / ')}`)].join('\n')}
function resetSetup(){state.phase='setup';$('#setupScreen').hidden=false;$('#stageScreen').hidden=true;$('#stageScreen').innerHTML='';renderExpansions();updateCounts()}
