let audioCtx=null,musicOn=false,musicNodes=[],musicTimer=null;
function ensureAudio(){if(!audioCtx)audioCtx=new(window.AudioContext||window.webkitAudioContext)();if(audioCtx.state==='suspended')audioCtx.resume()}
function startMusic(){ensureAudio();if(musicOn)return;musicOn=true;const master=audioCtx.createGain();master.gain.value=.10;master.connect(audioCtx.destination);musicNodes.push(master);[55,82.41,110].forEach((hz,i)=>{const o=audioCtx.createOscillator(),g=audioCtx.createGain(),f=audioCtx.createBiquadFilter();o.type=i===0?'sine':'triangle';o.frequency.value=hz;g.gain.value=i===0?.16:.035;f.type='lowpass';f.frequency.value=650+i*450;o.connect(f);f.connect(g);g.connect(master);o.start();musicNodes.push(o,g,f)});const notes=[146.83,164.81,174.61,196,220,246.94,261.63];const ping=()=>{if(!musicOn)return;const o=audioCtx.createOscillator(),g=audioCtx.createGain();o.type='sine';o.frequency.value=notes[Math.floor(Math.random()*notes.length)];const t=audioCtx.currentTime;g.gain.setValueAtTime(.0001,t);g.gain.exponentialRampToValueAtTime(.09,t+.35);g.gain.exponentialRampToValueAtTime(.0001,t+3.2);o.connect(g);g.connect(master);o.start(t);o.stop(t+3.3);musicTimer=setTimeout(ping,1900+Math.random()*2800)};ping();updateMusic()}
function stopMusic(){musicOn=false;clearTimeout(musicTimer);musicNodes.forEach(n=>{try{if(n.stop)n.stop();n.disconnect()}catch(e){}});musicNodes=[];updateMusic()}
function updateMusic(){$('#musicBtn').textContent=musicOn?'♪ Music On':'♪ Music Off';$('#musicBtn').style.color=musicOn?'var(--gold2)':''}
function playImpact(){try{ensureAudio();const o=audioCtx.createOscillator(),g=audioCtx.createGain();o.type='sine';const t=audioCtx.currentTime;o.frequency.setValueAtTime(84,t);o.frequency.exponentialRampToValueAtTime(34,t+.65);g.gain.setValueAtTime(.15,t);g.gain.exponentialRampToValueAtTime(.0001,t+.75);o.connect(g);g.connect(audioCtx.destination);o.start(t);o.stop(t+.8)}catch(e){}}
function toggleFullscreen(){document.body.classList.toggle('tv');if(!document.fullscreenElement){document.documentElement.requestFullscreen?.().catch(()=>{})}else document.exitFullscreen?.();$('#tvBtn').textContent=document.body.classList.contains('tv')?'▣ Exit TV':'▣ TV Mode'}
function initSpace(){const c=$('#space'),ctx=c.getContext('2d');let w,h,dpr,stars=[];function resize(){dpr=Math.min(devicePixelRatio||1,2);w=innerWidth;h=innerHeight;c.width=w*dpr;c.height=h*dpr;c.style.width=w+'px';c.style.height=h+'px';ctx.setTransform(dpr,0,0,dpr,0,0);stars=Array.from({length:Math.min(220,Math.floor(w*h/7000))},()=>({x:Math.random()*w,y:Math.random()*h,r:Math.random()*1.3+.25,a:Math.random()*.7+.2,p:Math.random()*6.28}))}function draw(t){ctx.clearRect(0,0,w,h);ctx.fillStyle='#03020a';ctx.fillRect(0,0,w,h);stars.forEach(s=>{const a=s.a*(.7+.3*Math.sin(t*.0007+s.p));ctx.beginPath();ctx.arc(s.x,s.y,s.r,0,Math.PI*2);ctx.fillStyle=`rgba(255,255,255,${a})`;ctx.fill()});requestAnimationFrame(draw)}addEventListener('resize',resize);resize();requestAnimationFrame(draw)}
function bind(){document.addEventListener('click',e=>{const exp=e.target.closest('[data-exp]');if(exp&&exp.dataset.exp!=='base'){state.exp.has(exp.dataset.exp)?state.exp.delete(exp.dataset.exp):state.exp.add(exp.dataset.exp);renderExpansions();return}const step=e.target.closest('[data-step]');if(step){state[step.dataset.step]+=Number(step.dataset.delta);updateCounts();return}const mode=e.target.closest('[data-mode]');if(mode){state.mode=mode.dataset.mode;$$('[data-mode]').forEach(x=>x.classList.toggle('active',x.dataset.mode===state.mode));return}const nav=e.target.closest('[data-view]');if(nav){switchView(nav.dataset.view);return}const filter=e.target.closest('[data-filter]');if(filter){state.guideFilter=filter.dataset.filter;renderFilters();renderGuide();return}const card=e.target.closest('.faction-card');if(card){if(state.phase==='pick'&&$('#setupView').classList.contains('active'))selectFaction(card.dataset.faction);else openFaction(card.dataset.faction)}});document.addEventListener('input',e=>{if(e.target.matches('[data-name]')){state.names[+e.target.dataset.name]=e.target.value;saveNames()}if(e.target.id==='guideSearch')renderGuide()});$('#launchBtn').onclick=begin;$('#rerollSeed').onclick=()=>setSeed(newSeed());$('#shareBtn').onclick=()=>copyText(draftUrl(),'Draft link copied');$('#musicBtn').onclick=()=>musicOn?stopMusic():startMusic();$('#tvBtn').onclick=toggleFullscreen;$('#modalClose').onclick=()=>$('#modal').classList.remove('open');$('#modal').onclick=e=>{if(e.target===$('#modal'))$('#modal').classList.remove('open')};addEventListener('keydown',e=>{if(e.key==='Escape')$('#modal').classList.remove('open')});document.addEventListener('fullscreenchange',()=>{if(!document.fullscreenElement&&document.body.classList.contains('tv')){document.body.classList.remove('tv');$('#tvBtn').textContent='▣ TV Mode'}})}
function init(){loadNames();setupFromUrl();if(!state.seed)setSeed(newSeed());else setSeed(state.seed);state.players=Math.max(2,Math.min(8,state.players));state.perPlayer=Math.max(1,Math.min(5,state.perPlayer));renderExpansions();updateCounts();$$('[data-mode]').forEach(x=>x.classList.toggle('active',x.dataset.mode===state.mode));renderFilters();bind();initSpace()}
init();
