let audioCtx=null,musicOn=false,musicNodes=[],musicTimer=null,musicMaster=null;
function ensureAudio(){if(!audioCtx)audioCtx=new(window.AudioContext||window.webkitAudioContext)();if(audioCtx.state==='suspended')audioCtx.resume()}
function makeNoise(duration=1){const len=Math.max(1,Math.floor(audioCtx.sampleRate*duration)),buffer=audioCtx.createBuffer(1,len,audioCtx.sampleRate),data=buffer.getChannelData(0);for(let i=0;i<len;i++)data[i]=Math.random()*2-1;return buffer}
function startMusic(){ensureAudio();if(musicOn)return;musicOn=true;
  const master=audioCtx.createGain(),tone=audioCtx.createBiquadFilter(),comp=audioCtx.createDynamicsCompressor();musicMaster=master;master.gain.value=.155;tone.type='lowpass';tone.frequency.value=2500;tone.Q.value=.35;comp.threshold.value=-22;comp.knee.value=16;comp.ratio.value=3;comp.attack.value=.018;comp.release.value=.28;master.connect(tone);tone.connect(comp);comp.connect(audioCtx.destination);musicNodes.push(master,tone,comp);
  const vinyl=audioCtx.createBufferSource(),vinylHP=audioCtx.createBiquadFilter(),vinylLP=audioCtx.createBiquadFilter(),vinylGain=audioCtx.createGain();vinyl.buffer=makeNoise(2.5);vinyl.loop=true;vinylHP.type='highpass';vinylHP.frequency.value=180;vinylLP.type='lowpass';vinylLP.frequency.value=1650;vinylGain.gain.value=.006;vinyl.connect(vinylHP);vinylHP.connect(vinylLP);vinylLP.connect(vinylGain);vinylGain.connect(master);vinyl.start();musicNodes.push(vinyl,vinylHP,vinylLP,vinylGain);
  const bpm=76,beat=60/bpm,step=beat/2,progression=[
    {root:55,chord:[220,261.63,329.63,392]},
    {root:43.65,chord:[174.61,220,261.63,329.63]},
    {root:49,chord:[196,246.94,293.66,349.23]},
    {root:41.2,chord:[164.81,196,246.94,293.66]}
  ];
  const kick=(at,level=1)=>{const o=audioCtx.createOscillator(),g=audioCtx.createGain(),f=audioCtx.createBiquadFilter();o.type='sine';o.frequency.setValueAtTime(92,at);o.frequency.exponentialRampToValueAtTime(42,at+.18);f.type='lowpass';f.frequency.value=220;g.gain.setValueAtTime(.0001,at);g.gain.exponentialRampToValueAtTime(.115*level,at+.012);g.gain.exponentialRampToValueAtTime(.0001,at+.42);o.connect(f);f.connect(g);g.connect(master);o.start(at);o.stop(at+.45)};
  const snare=(at,ghost=false)=>{const n=audioCtx.createBufferSource(),bp=audioCtx.createBiquadFilter(),lp=audioCtx.createBiquadFilter(),g=audioCtx.createGain(),body=audioCtx.createOscillator(),bg=audioCtx.createGain();n.buffer=makeNoise(.22);bp.type='bandpass';bp.frequency.value=1050;bp.Q.value=.8;lp.type='lowpass';lp.frequency.value=1900;g.gain.setValueAtTime(.0001,at);g.gain.exponentialRampToValueAtTime(ghost?.013:.026,at+.016);g.gain.exponentialRampToValueAtTime(.0001,at+.19);n.connect(bp);bp.connect(lp);lp.connect(g);g.connect(master);n.start(at);n.stop(at+.22);body.type='triangle';body.frequency.value=155;bg.gain.setValueAtTime(.0001,at);bg.gain.exponentialRampToValueAtTime(ghost?.006:.012,at+.012);bg.gain.exponentialRampToValueAtTime(.0001,at+.16);body.connect(bg);bg.connect(master);body.start(at);body.stop(at+.18)};
  const hat=at=>{const n=audioCtx.createBufferSource(),hp=audioCtx.createBiquadFilter(),lp=audioCtx.createBiquadFilter(),g=audioCtx.createGain();n.buffer=makeNoise(.08);hp.type='highpass';hp.frequency.value=2400;lp.type='lowpass';lp.frequency.value=5200;g.gain.setValueAtTime(.0001,at);g.gain.exponentialRampToValueAtTime(.0045,at+.008);g.gain.exponentialRampToValueAtTime(.0001,at+.065);n.connect(hp);hp.connect(lp);lp.connect(g);g.connect(master);n.start(at);n.stop(at+.08)};
  const bass=(at,freq,level=.042)=>{const o=audioCtx.createOscillator(),g=audioCtx.createGain(),f=audioCtx.createBiquadFilter();o.type='triangle';o.frequency.value=freq;f.type='lowpass';f.frequency.value=260;f.Q.value=.6;g.gain.setValueAtTime(.0001,at);g.gain.exponentialRampToValueAtTime(level,at+.035);g.gain.exponentialRampToValueAtTime(level*.46,at+.28);g.gain.exponentialRampToValueAtTime(.0001,at+.72);o.connect(f);f.connect(g);g.connect(master);o.start(at);o.stop(at+.76)};
  const chord=(at,freqs)=>{const bus=audioCtx.createGain(),f=audioCtx.createBiquadFilter();bus.gain.value=1;f.type='lowpass';f.frequency.value=1180;f.Q.value=.55;bus.connect(f);f.connect(master);freqs.forEach((freq,i)=>{const o=audioCtx.createOscillator(),g=audioCtx.createGain();o.type=i%2?'sine':'triangle';o.frequency.value=freq;o.detune.value=(i-1.5)*3;g.gain.setValueAtTime(.0001,at);g.gain.exponentialRampToValueAtTime(i===0?.013:.009,at+.11+i*.012);g.gain.setValueAtTime(i===0?.010:.007,at+.72);g.gain.exponentialRampToValueAtTime(.0001,at+2.7);o.connect(g);g.connect(bus);o.start(at);o.stop(at+2.8)})};
  const dust=at=>{const o=audioCtx.createOscillator(),g=audioCtx.createGain(),f=audioCtx.createBiquadFilter();o.type='sine';o.frequency.value=[293.66,329.63,392][Math.floor(Math.random()*3)];f.type='lowpass';f.frequency.value=900;g.gain.setValueAtTime(.0001,at);g.gain.exponentialRampToValueAtTime(.005,at+.18);g.gain.exponentialRampToValueAtTime(.0001,at+1.6);o.connect(f);f.connect(g);g.connect(master);o.start(at);o.stop(at+1.7)};
  let stepIndex=0,nextTime=audioCtx.currentTime+.08;
  const schedule=()=>{if(!musicOn)return;while(nextTime<audioCtx.currentTime+.36){const s=stepIndex%8,bar=Math.floor(stepIndex/8)%4,p=progression[bar],swing=s%2?.026:0,at=nextTime+swing;if(s===0){kick(at,1);bass(at,p.root,.046);chord(at,p.chord)}if(s===2)snare(at);if(s===4){kick(at,.78);bass(at,p.root,.035)}if(s===6)snare(at);if(s===7&&bar%2===1)kick(at,.28);if(s===5&&bar===3)snare(at,true);hat(at);if((s===3||s===7)&&Math.random()>.66)dust(at+.04);stepIndex++;nextTime+=step}}
  schedule();musicTimer=setInterval(schedule,90);updateMusic()}
function stopMusic(){musicOn=false;clearInterval(musicTimer);musicTimer=null;if(musicMaster){try{const t=audioCtx.currentTime;musicMaster.gain.cancelScheduledValues(t);musicMaster.gain.setTargetAtTime(.0001,t,.04)}catch(e){}}setTimeout(()=>{musicNodes.forEach(n=>{try{if(n.stop)n.stop();n.disconnect()}catch(e){}});musicNodes=[];musicMaster=null},180);updateMusic()}
function updateMusic(){$('#musicBtn').textContent=musicOn?'♪ Lofi On':'♪ Lofi Off';$('#musicBtn').style.color=musicOn?'var(--gold2)':''}
function duckMusic(duration=4.2){if(!musicOn||!musicMaster)return;const t=audioCtx.currentTime;try{musicMaster.gain.cancelScheduledValues(t);musicMaster.gain.setValueAtTime(Math.max(.001,musicMaster.gain.value),t);musicMaster.gain.linearRampToValueAtTime(.035,t+.22);musicMaster.gain.setValueAtTime(.035,t+Math.max(.5,duration-.85));musicMaster.gain.linearRampToValueAtTime(.155,t+duration)}catch(e){}}
function playFactionStinger(){try{ensureAudio();duckMusic(4.4);const t=audioCtx.currentTime,hit=t+.92,master=audioCtx.createGain(),lp=audioCtx.createBiquadFilter(),comp=audioCtx.createDynamicsCompressor();master.gain.value=.96;lp.type='lowpass';lp.frequency.value=930;lp.Q.value=.45;comp.threshold.value=-21;comp.knee.value=20;comp.ratio.value=4.5;comp.attack.value=.012;comp.release.value=.42;master.connect(lp);lp.connect(comp);comp.connect(audioCtx.destination);
  const swell=audioCtx.createOscillator(),sg=audioCtx.createGain(),sf=audioCtx.createBiquadFilter();swell.type='sawtooth';swell.frequency.setValueAtTime(34,t);swell.frequency.exponentialRampToValueAtTime(68,hit);sf.type='lowpass';sf.frequency.setValueAtTime(120,t);sf.frequency.exponentialRampToValueAtTime(420,hit);sg.gain.setValueAtTime(.0001,t);sg.gain.exponentialRampToValueAtTime(.038,t+.34);sg.gain.exponentialRampToValueAtTime(.085,hit-.06);sg.gain.exponentialRampToValueAtTime(.0001,hit+.62);swell.connect(sf);sf.connect(sg);sg.connect(master);swell.start(t);swell.stop(hit+.7);
  const rumble=audioCtx.createBufferSource(),rf=audioCtx.createBiquadFilter(),rg=audioCtx.createGain();rumble.buffer=makeNoise(2.2);rf.type='lowpass';rf.frequency.setValueAtTime(72,t);rf.frequency.exponentialRampToValueAtTime(190,hit+.45);rg.gain.setValueAtTime(.0001,t);rg.gain.exponentialRampToValueAtTime(.025,t+.38);rg.gain.exponentialRampToValueAtTime(.048,hit+.08);rg.gain.exponentialRampToValueAtTime(.0001,hit+1.25);rumble.connect(rf);rf.connect(rg);rg.connect(master);rumble.start(t);rumble.stop(hit+1.35);
  const sub=audioCtx.createOscillator(),subg=audioCtx.createGain();sub.type='sine';sub.frequency.setValueAtTime(51,hit);sub.frequency.exponentialRampToValueAtTime(22,hit+3.35);subg.gain.setValueAtTime(.0001,hit);subg.gain.exponentialRampToValueAtTime(.36,hit+.09);subg.gain.exponentialRampToValueAtTime(.18,hit+.86);subg.gain.exponentialRampToValueAtTime(.0001,hit+3.45);sub.connect(subg);subg.connect(master);sub.start(hit);sub.stop(hit+3.5);
  [[49,'sawtooth',.12,340],[73.42,'triangle',.075,430],[98,'triangle',.038,520],[146.83,'sine',.014,650]].forEach(([freq,type,level,cut],i)=>{const o=audioCtx.createOscillator(),g=audioCtx.createGain(),f=audioCtx.createBiquadFilter();o.type=type;o.frequency.value=freq;f.type='lowpass';f.frequency.value=cut;f.Q.value=.55;g.gain.setValueAtTime(.0001,hit-.04);g.gain.exponentialRampToValueAtTime(level,hit+.14+i*.025);g.gain.setValueAtTime(level*.58,hit+1.45);g.gain.exponentialRampToValueAtTime(.0001,hit+4.0);o.connect(f);f.connect(g);g.connect(master);o.start(hit-.05);o.stop(hit+4.1)});
  const tail=audioCtx.createOscillator(),tg=audioCtx.createGain(),tf=audioCtx.createBiquadFilter();tail.type='triangle';tail.frequency.setValueAtTime(38.9,hit+.42);tail.frequency.exponentialRampToValueAtTime(27.5,hit+4.5);tf.type='lowpass';tf.frequency.value=230;tg.gain.setValueAtTime(.0001,hit+.38);tg.gain.exponentialRampToValueAtTime(.058,hit+.72);tg.gain.exponentialRampToValueAtTime(.0001,hit+4.6);tail.connect(tf);tf.connect(tg);tg.connect(master);tail.start(hit+.38);tail.stop(hit+4.7)
}catch(e){}}
function playCouncilStinger(){try{ensureAudio();const t=audioCtx.currentTime,master=audioCtx.createGain(),lp=audioCtx.createBiquadFilter();master.gain.value=.62;lp.type='lowpass';lp.frequency.value=760;master.connect(lp);lp.connect(audioCtx.destination);[43.65,65.41,87.31].forEach((freq,i)=>{const o=audioCtx.createOscillator(),g=audioCtx.createGain();o.type=i===0?'sine':'triangle';o.frequency.value=freq;g.gain.setValueAtTime(.0001,t);g.gain.exponentialRampToValueAtTime(i===0?.12:.048,t+.09+i*.05);g.gain.exponentialRampToValueAtTime(.0001,t+1.8);o.connect(g);g.connect(master);o.start(t);o.stop(t+1.85)});const boom=audioCtx.createOscillator(),bg=audioCtx.createGain();boom.type='sine';boom.frequency.setValueAtTime(50,t+.14);boom.frequency.exponentialRampToValueAtTime(29,t+1.3);bg.gain.setValueAtTime(.0001,t+.14);bg.gain.exponentialRampToValueAtTime(.09,t+.24);bg.gain.exponentialRampToValueAtTime(.0001,t+1.35);boom.connect(bg);bg.connect(master);boom.start(t+.13);boom.stop(t+1.4)}catch(e){}}
function playImpact(){playCouncilStinger()}
function toggleFullscreen(){document.body.classList.toggle('tv');if(!document.fullscreenElement){document.documentElement.requestFullscreen?.().catch(()=>{})}else document.exitFullscreen?.();$('#tvBtn').textContent=document.body.classList.contains('tv')?'▣ Exit TV':'▣ TV Mode'}
function initSpace(){const c=$('#space'),ctx=c.getContext('2d'),root=document.documentElement,reduced=matchMedia('(prefers-reduced-motion: reduce)').matches;let w,h,dpr,stars=[],pointer={x:.5,y:.45,tx:.5,ty:.45},last=0;function resize(){dpr=Math.min(devicePixelRatio||1,2);w=innerWidth;h=innerHeight;c.width=w*dpr;c.height=h*dpr;c.style.width=w+'px';c.style.height=h+'px';ctx.setTransform(dpr,0,0,dpr,0,0);stars=Array.from({length:Math.min(280,Math.floor(w*h/5600))},()=>({x:Math.random()*w,y:Math.random()*h,r:Math.random()*1.45+.18,a:Math.random()*.68+.18,p:Math.random()*6.28,v:(Math.random()*.18+.035)*(Math.random()>.5?1:-1)}))}function setPointer(x,y){if(reduced)return;pointer.tx=Math.min(1,Math.max(0,x/Math.max(1,w)));pointer.ty=Math.min(1,Math.max(0,y/Math.max(1,h)))}function nebula(cx,cy,r,inner,middle){const g=ctx.createRadialGradient(cx,cy,0,cx,cy,r);g.addColorStop(0,inner);g.addColorStop(.38,middle);g.addColorStop(1,'rgba(3,2,10,0)');ctx.fillStyle=g;ctx.fillRect(-120,-120,w+240,h+240)}function draw(t){const dt=Math.min(34,last?t-last:16.7);last=t;const ease=reduced?0:1-Math.pow(.0015,dt/1000);pointer.x+=((reduced?.5:pointer.tx)-pointer.x)*ease;pointer.y+=((reduced?.45:pointer.ty)-pointer.y)*ease;const px=(pointer.x-.5),py=(pointer.y-.5),driftX=reduced?0:Math.sin(t*.00011)*.045+Math.cos(t*.000057)*.02,driftY=reduced?0:Math.cos(t*.00009)*.04+Math.sin(t*.000073)*.018;root.style.setProperty('--nebula-tx',`${(px*28).toFixed(1)}px`);root.style.setProperty('--nebula-ty',`${(py*22).toFixed(1)}px`);root.style.setProperty('--nebula-mix-x',`${(50+px*16).toFixed(1)}%`);root.style.setProperty('--nebula-mix-y',`${(45+py*13).toFixed(1)}%`);ctx.clearRect(0,0,w,h);ctx.fillStyle='#03020a';ctx.fillRect(0,0,w,h);const scale=Math.max(w,h);ctx.globalCompositeOperation='screen';nebula(w*(.20+driftX)-px*45,h*(.22+driftY)-py*34,scale*.53,'rgba(102,44,182,.22)','rgba(62,24,126,.11)');nebula(w*(.77-driftX*.6)+px*56,h*(.34-driftY*.4)+py*42,scale*.47,'rgba(28,91,198,.19)','rgba(24,44,116,.10)');nebula(w*(.56+driftX*.4)-px*34,h*(.82-driftY*.8)-py*48,scale*.50,'rgba(157,38,124,.15)','rgba(84,20,93,.08)');nebula(w*(.49-driftX*.5)+px*22,h*(.50+driftY*.5)+py*16,scale*.34,'rgba(196,145,55,.045)','rgba(110,71,28,.018)');ctx.globalCompositeOperation='source-over';stars.forEach(s=>{if(!reduced){s.x+=s.v*.018*dt;if(s.x<-.5)s.x=w+.5;else if(s.x>w+.5)s.x=-.5}const a=s.a*(.68+.32*Math.sin(t*.0007+s.p)),depth=.6+s.r*.85,x=s.x+px*7*depth,y=s.y+py*6*depth;ctx.beginPath();ctx.arc(x,y,s.r,0,Math.PI*2);ctx.fillStyle=`rgba(255,255,255,${a})`;ctx.fill()});requestAnimationFrame(draw)}addEventListener('resize',resize);addEventListener('pointermove',e=>setPointer(e.clientX,e.clientY),{passive:true});addEventListener('pointerleave',()=>{pointer.tx=.5;pointer.ty=.45});resize();requestAnimationFrame(draw)}
function bind(){document.addEventListener('click',e=>{const exp=e.target.closest('[data-exp]');if(exp&&exp.dataset.exp!=='base'){state.exp.has(exp.dataset.exp)?state.exp.delete(exp.dataset.exp):state.exp.add(exp.dataset.exp);renderExpansions();return}const step=e.target.closest('[data-step]');if(step){state[step.dataset.step]+=Number(step.dataset.delta);updateCounts();return}const nav=e.target.closest('[data-view]');if(nav){switchView(nav.dataset.view);return}const filter=e.target.closest('[data-filter]');if(filter){state.guideFilter=filter.dataset.filter;renderFilters();renderGuide();return}const card=e.target.closest('.faction-card');if(card){if(state.phase==='pick'&&$('#setupView').classList.contains('active'))selectFaction(card.dataset.faction);else openFaction(card.dataset.faction)}});document.addEventListener('input',e=>{if(e.target.matches('[data-name]')){state.names[+e.target.dataset.name]=e.target.value;saveNames()}if(e.target.id==='guideSearch')renderGuide()});$('#launchBtn').onclick=begin;$('#rerollSeed').onclick=()=>setSeed(newSeed());$('#shareBtn').onclick=()=>copyText(draftUrl(),'Draft link copied');$('#musicBtn').onclick=()=>musicOn?stopMusic():startMusic();$('#tvBtn').onclick=toggleFullscreen;$('#modalClose').onclick=()=>$('#modal').classList.remove('open');$('#modal').onclick=e=>{if(e.target===$('#modal'))$('#modal').classList.remove('open')};addEventListener('keydown',e=>{if(e.key==='Escape')$('#modal').classList.remove('open')});document.addEventListener('fullscreenchange',()=>{if(!document.fullscreenElement&&document.body.classList.contains('tv')){document.body.classList.remove('tv');$('#tvBtn').textContent='▣ TV Mode'}})}
function init(){loadNames();setupFromUrl();if(!state.seed)setSeed(newSeed());else setSeed(state.seed);state.players=Math.max(2,Math.min(8,state.players));state.perPlayer=Math.max(1,Math.min(5,state.perPlayer));renderExpansions();updateCounts();renderFilters();bind();initSpace()}
init();
