let audioCtx=null,musicOn=false,musicNodes=[],musicTimer=null;
function ensureAudio(){if(!audioCtx)audioCtx=new(window.AudioContext||window.webkitAudioContext)();if(audioCtx.state==='suspended')audioCtx.resume()}
function startMusic(){ensureAudio();if(musicOn)return;musicOn=true;const master=audioCtx.createGain();master.gain.value=.10;master.connect(audioCtx.destination);musicNodes.push(master);[55,82.41,110].forEach((hz,i)=>{const o=audioCtx.createOscillator(),g=audioCtx.createGain(),f=audioCtx.createBiquadFilter();o.type=i===0?'sine':'triangle';o.frequency.value=hz;g.gain.value=i===0?.16:.035;f.type='lowpass';f.frequency.value=650+i*450;o.connect(f);f.connect(g);g.connect(master);o.start();musicNodes.push(o,g,f)});const notes=[146.83,164.81,174.61,196,220,246.94,261.63];const ping=()=>{if(!musicOn)return;const o=audioCtx.createOscillator(),g=audioCtx.createGain();o.type='sine';o.frequency.value=notes[Math.floor(Math.random()*notes.length)];const t=audioCtx.currentTime;g.gain.setValueAtTime(.0001,t);g.gain.exponentialRampToValueAtTime(.09,t+.35);g.gain.exponentialRampToValueAtTime(.0001,t+3.2);o.connect(g);g.connect(master);o.start(t);o.stop(t+3.3);musicTimer=setTimeout(ping,1900+Math.random()*2800)};ping();updateMusic()}
function stopMusic(){musicOn=false;clearTimeout(musicTimer);musicNodes.forEach(n=>{try{if(n.stop)n.stop();n.disconnect()}catch(e){}});musicNodes=[];updateMusic()}
function updateMusic(){$('#musicBtn').textContent=musicOn?'♪ Music On':'♪ Music Off';$('#musicBtn').style.color=musicOn?'var(--gold2)':''}
function makeNoise(duration=1){const len=Math.max(1,Math.floor(audioCtx.sampleRate*duration)),buffer=audioCtx.createBuffer(1,len,audioCtx.sampleRate),data=buffer.getChannelData(0);for(let i=0;i<len;i++)data[i]=Math.random()*2-1;return buffer}
function playFactionStinger(){try{ensureAudio();const t=audioCtx.currentTime,master=audioCtx.createGain(),comp=audioCtx.createDynamicsCompressor();master.gain.value=.78;comp.threshold.value=-18;comp.knee.value=18;comp.ratio.value=4;master.connect(comp);comp.connect(audioCtx.destination);
  const rise=audioCtx.createOscillator(),riseGain=audioCtx.createGain(),riseFilter=audioCtx.createBiquadFilter();rise.type='sawtooth';rise.frequency.setValueAtTime(115,t);rise.frequency.exponentialRampToValueAtTime(620,t+1.05);riseFilter.type='lowpass';riseFilter.frequency.setValueAtTime(420,t);riseFilter.frequency.exponentialRampToValueAtTime(2800,t+1.05);riseGain.gain.setValueAtTime(.0001,t);riseGain.gain.exponentialRampToValueAtTime(.055,t+.3);riseGain.gain.exponentialRampToValueAtTime(.0001,t+1.2);rise.connect(riseFilter);riseFilter.connect(riseGain);riseGain.connect(master);rise.start(t);rise.stop(t+1.25);
  const noise=audioCtx.createBufferSource(),noiseFilter=audioCtx.createBiquadFilter(),noiseGain=audioCtx.createGain();noise.buffer=makeNoise(1.1);noiseFilter.type='bandpass';noiseFilter.Q.value=.8;noiseFilter.frequency.setValueAtTime(300,t);noiseFilter.frequency.exponentialRampToValueAtTime(3600,t+.9);noiseGain.gain.setValueAtTime(.0001,t);noiseGain.gain.exponentialRampToValueAtTime(.045,t+.38);noiseGain.gain.exponentialRampToValueAtTime(.0001,t+1.05);noise.connect(noiseFilter);noiseFilter.connect(noiseGain);noiseGain.connect(master);noise.start(t);noise.stop(t+1.1);
  const boom=audioCtx.createOscillator(),boomGain=audioCtx.createGain();boom.type='sine';boom.frequency.setValueAtTime(78,t+.68);boom.frequency.exponentialRampToValueAtTime(28,t+2.15);boomGain.gain.setValueAtTime(.0001,t+.66);boomGain.gain.exponentialRampToValueAtTime(.28,t+.73);boomGain.gain.exponentialRampToValueAtTime(.0001,t+2.2);boom.connect(boomGain);boomGain.connect(master);boom.start(t+.66);boom.stop(t+2.25);
  [110,164.81,220].forEach((freq,i)=>{const o=audioCtx.createOscillator(),g=audioCtx.createGain(),f=audioCtx.createBiquadFilter();o.type=i===0?'triangle':'sawtooth';o.frequency.value=freq;f.type='lowpass';f.frequency.value=900+i*350;g.gain.setValueAtTime(.0001,t+.68);g.gain.exponentialRampToValueAtTime(i===0?.085:.035,t+.78);g.gain.exponentialRampToValueAtTime(.0001,t+2.75);o.connect(f);f.connect(g);g.connect(master);o.start(t+.68);o.stop(t+2.8)});
  [659.25,987.77].forEach((freq,i)=>{const o=audioCtx.createOscillator(),g=audioCtx.createGain();o.type='sine';o.frequency.value=freq;const start=t+.9+i*.11;g.gain.setValueAtTime(.0001,start);g.gain.exponentialRampToValueAtTime(.055,start+.035);g.gain.exponentialRampToValueAtTime(.0001,start+2.2);o.connect(g);g.connect(master);o.start(start);o.stop(start+2.25)});
}catch(e){}}
function playCouncilStinger(){try{ensureAudio();const t=audioCtx.currentTime;[65.41,98,130.81].forEach((freq,i)=>{const o=audioCtx.createOscillator(),g=audioCtx.createGain();o.type=i?'triangle':'sine';o.frequency.value=freq;g.gain.setValueAtTime(.0001,t);g.gain.exponentialRampToValueAtTime(i===0?.12:.045,t+.08+i*.04);g.gain.exponentialRampToValueAtTime(.0001,t+1.35);o.connect(g);g.connect(audioCtx.destination);o.start(t);o.stop(t+1.4)})}catch(e){}}
function playImpact(){playCouncilStinger()}
function toggleFullscreen(){document.body.classList.toggle('tv');if(!document.fullscreenElement){document.documentElement.requestFullscreen?.().catch(()=>{})}else document.exitFullscreen?.();$('#tvBtn').textContent=document.body.classList.contains('tv')?'▣ Exit TV':'▣ TV Mode'}
function initSpace(){const c=$('#space'),ctx=c.getContext('2d');let w,h,dpr,stars=[];function resize(){dpr=Math.min(devicePixelRatio||1,2);w=innerWidth;h=innerHeight;c.width=w*dpr;c.height=h*dpr;c.style.width=w+'px';c.style.height=h+'px';ctx.setTransform(dpr,0,0,dpr,0,0);stars=Array.from({length:Math.min(220,Math.floor(w*h/7000))},()=>({x:Math.random()*w,y:Math.random()*h,r:Math.random()*1.3+.25,a:Math.random()*.7+.2,p:Math.random()*6.28}))}function draw(t){ctx.clearRect(0,0,w,h);ctx.fillStyle='#03020a';ctx.fillRect(0,0,w,h);stars.forEach(s=>{const a=s.a*(.7+.3*Math.sin(t*.0007+s.p));ctx.beginPath();ctx.arc(s.x,s.y,s.r,0,Math.PI*2);ctx.fillStyle=`rgba(255,255,255,${a})`;ctx.fill()});requestAnimationFrame(draw)}addEventListener('resize',resize);resize();requestAnimationFrame(draw)}
function bind(){document.addEventListener('click',e=>{const exp=e.target.closest('[data-exp]');if(exp&&exp.dataset.exp!=='base'){state.exp.has(exp.dataset.exp)?state.exp.delete(exp.dataset.exp):state.exp.add(exp.dataset.exp);renderExpansions();return}const step=e.target.closest('[data-step]');if(step){state[step.dataset.step]+=Number(step.dataset.delta);updateCounts();return}const nav=e.target.closest('[data-view]');if(nav){switchView(nav.dataset.view);return}const filter=e.target.closest('[data-filter]');if(filter){state.guideFilter=filter.dataset.filter;renderFilters();renderGuide();return}const card=e.target.closest('.faction-card');if(card){if(state.phase==='pick'&&$('#setupView').classList.contains('active'))selectFaction(card.dataset.faction);else openFaction(card.dataset.faction)}});document.addEventListener('input',e=>{if(e.target.matches('[data-name]')){state.names[+e.target.dataset.name]=e.target.value;saveNames()}if(e.target.id==='guideSearch')renderGuide()});$('#launchBtn').onclick=begin;$('#rerollSeed').onclick=()=>setSeed(newSeed());$('#shareBtn').onclick=()=>copyText(draftUrl(),'Draft link copied');$('#musicBtn').onclick=()=>musicOn?stopMusic():startMusic();$('#tvBtn').onclick=toggleFullscreen;$('#modalClose').onclick=()=>$('#modal').classList.remove('open');$('#modal').onclick=e=>{if(e.target===$('#modal'))$('#modal').classList.remove('open')};addEventListener('keydown',e=>{if(e.key==='Escape')$('#modal').classList.remove('open')});document.addEventListener('fullscreenchange',()=>{if(!document.fullscreenElement&&document.body.classList.contains('tv')){document.body.classList.remove('tv');$('#tvBtn').textContent='▣ TV Mode'}})}
function init(){loadNames();setupFromUrl();if(!state.seed)setSeed(newSeed());else setSeed(state.seed);state.players=Math.max(2,Math.min(8,state.players));state.perPlayer=Math.max(1,Math.min(5,state.perPlayer));renderExpansions();updateCounts();renderFilters();bind();initSpace()}
init();
