const SOUNDTRACK_VOLUME_KEY='ti4-council-music-volume-v1';
const SOUNDTRACK_API=location.hostname==='loafer87.github.io'?'https://twilight-drafter-overview.vercel.app/api/music':'/api/music';
const SOUNDTRACKS={
  event:{label:'Event Horizon',src:`${SOUNDTRACK_API}?track=event`},
  cathedral:{label:'Cathedral of the Void',src:`${SOUNDTRACK_API}?track=cathedral`}
};
const proceduralStartMusic=startMusic,proceduralStopMusic=stopMusic,proceduralDuckMusic=duckMusic;
let soundtrackVolume=Math.max(.05,Math.min(1,Number(localStorage.getItem(SOUNDTRACK_VOLUME_KEY))||.35));
let soundtrackDuckLevel=1,soundtrackCurrent='event',soundtrackFallback=false,soundtrackFadeRaf=0,soundtrackLevelRaf=0,soundtrackDuckTimer=null;
const soundtrackMix={event:1,cathedral:0};
const soundtrackAudio={};
Object.entries(SOUNDTRACKS).forEach(([key,track])=>{const a=new Audio();a.src=track.src;a.loop=true;a.preload='none';a.playsInline=true;a.dataset.track=key;soundtrackAudio[key]=a});
function soundtrackClamp(v){return Math.max(0,Math.min(1,v))}
function soundtrackApplyVolume(){Object.keys(soundtrackAudio).forEach(key=>{soundtrackAudio[key].volume=soundtrackClamp(soundtrackVolume*soundtrackDuckLevel*(soundtrackMix[key]||0))});if(soundtrackFallback&&musicMaster&&audioCtx){try{const target=.16*(soundtrackVolume/.35);musicMaster.gain.setTargetAtTime(Math.max(.01,Math.min(.35,target)),audioCtx.currentTime,.04)}catch(e){}}}
function soundtrackSetLabel(){const btn=$('#musicBtn');if(!btn)return;btn.textContent=musicOn?'♪ Soundtrack On':'♪ Soundtrack Off';btn.style.color=musicOn?'var(--gold2)':'';btn.title=musicOn?`Now playing: ${SOUNDTRACKS[soundtrackCurrent]?.label||'Council score'}`:'Play the Council soundtrack';const control=$('.music-volume-control');if(control)control.classList.toggle('muted',!musicOn)}
function soundtrackEnsureVolumeControl(){const btn=$('#musicBtn');if(!btn||$('.music-volume-control'))return;const wrap=document.createElement('label');wrap.className='music-volume-control';wrap.title='Soundtrack playback volume';wrap.innerHTML=`<span id="musicVolumeLabel">Music ${Math.round(soundtrackVolume*100)}%</span><input id="musicVolume" type="range" min="5" max="100" step="5" value="${Math.round(soundtrackVolume*100)}" aria-label="Soundtrack volume">`;btn.insertAdjacentElement('afterend',wrap);const slider=$('#musicVolume');slider.addEventListener('input',()=>{soundtrackVolume=Math.max(.05,Math.min(1,Number(slider.value)/100));localStorage.setItem(SOUNDTRACK_VOLUME_KEY,String(soundtrackVolume));$('#musicVolumeLabel').textContent=`Music ${Math.round(soundtrackVolume*100)}%`;soundtrackApplyVolume()})}
function soundtrackAnimateMix(target,duration=2200){cancelAnimationFrame(soundtrackFadeRaf);const start=performance.now(),from={...soundtrackMix};function frame(now){const p=Math.min(1,(now-start)/duration),ease=p<.5?2*p*p:1-Math.pow(-2*p+2,2)/2;Object.keys(soundtrackMix).forEach(key=>{const goal=key===target?1:0;soundtrackMix[key]=from[key]+(goal-from[key])*ease});soundtrackApplyVolume();if(p<1)soundtrackFadeRaf=requestAnimationFrame(frame);else Object.keys(soundtrackAudio).forEach(key=>{if(key!==target&&soundtrackMix[key]<.01)soundtrackAudio[key].pause()})}soundtrackFadeRaf=requestAnimationFrame(frame)}
function soundtrackAnimateLevel(target,duration=300){cancelAnimationFrame(soundtrackLevelRaf);const start=performance.now(),from=soundtrackDuckLevel;function frame(now){const p=Math.min(1,(now-start)/duration),ease=1-Math.pow(1-p,3);soundtrackDuckLevel=from+(target-from)*ease;soundtrackApplyVolume();if(p<1)soundtrackLevelRaf=requestAnimationFrame(frame)}soundtrackLevelRaf=requestAnimationFrame(frame)}
async function soundtrackPlayTrack(key,reset=false){const a=soundtrackAudio[key];if(!a)return false;if(reset)try{a.currentTime=0}catch(e){}try{await a.play();return true}catch(e){console.warn('Real soundtrack unavailable',e);return false}}
function soundtrackUseFallback(){if(soundtrackFallback)return;soundtrackFallback=true;Object.values(soundtrackAudio).forEach(a=>{try{a.pause()}catch(e){}});musicOn=false;proceduralStartMusic();toast('Real soundtrack unavailable • procedural score engaged');soundtrackSetLabel()}
async function startMusic(){if(musicOn)return;musicOn=true;soundtrackFallback=false;soundtrackMix.event=soundtrackCurrent==='event'?1:0;soundtrackMix.cathedral=soundtrackCurrent==='cathedral'?1:0;soundtrackDuckLevel=1;soundtrackApplyVolume();soundtrackSetLabel();const ok=await soundtrackPlayTrack(soundtrackCurrent,false);if(!ok){soundtrackUseFallback();return}const other=soundtrackCurrent==='event'?'cathedral':'event';soundtrackAudio[other].preload='auto';try{soundtrackAudio[other].load()}catch(e){}}
function stopMusic(){clearTimeout(soundtrackDuckTimer);soundtrackDuckTimer=null;if(soundtrackFallback){proceduralStopMusic();soundtrackFallback=false;soundtrackSetLabel();return}musicOn=false;cancelAnimationFrame(soundtrackFadeRaf);cancelAnimationFrame(soundtrackLevelRaf);const from={...soundtrackMix},start=performance.now();function frame(now){const p=Math.min(1,(now-start)/320);Object.keys(soundtrackMix).forEach(key=>soundtrackMix[key]=from[key]*(1-p));soundtrackApplyVolume();if(p<1)requestAnimationFrame(frame);else{Object.values(soundtrackAudio).forEach(a=>a.pause());soundtrackMix[soundtrackCurrent]=1}}requestAnimationFrame(frame);soundtrackSetLabel()}
function updateMusic(){soundtrackSetLabel()}
async function setSoundtrack(key,duration=2200){if(!SOUNDTRACKS[key]||key===soundtrackCurrent)return;soundtrackCurrent=key;soundtrackSetLabel();if(!musicOn||soundtrackFallback){soundtrackMix.event=key==='event'?1:0;soundtrackMix.cathedral=key==='cathedral'?1:0;return}const ok=await soundtrackPlayTrack(key,true);if(!ok)return;soundtrackAnimateMix(key,duration)}
function duckMusic(duration=4){if(soundtrackFallback){proceduralDuckMusic(duration);return}if(!musicOn)return;clearTimeout(soundtrackDuckTimer);soundtrackAnimateLevel(.12,180);soundtrackDuckTimer=setTimeout(()=>restoreMusic(),Math.max(.5,duration)*1000)}
function restoreMusic(){clearTimeout(soundtrackDuckTimer);soundtrackDuckTimer=null;if(soundtrackFallback){if(musicOn&&musicMaster&&audioCtx){try{const target=.16*(soundtrackVolume/.35),t=audioCtx.currentTime;musicMaster.gain.cancelScheduledValues(t);musicMaster.gain.setValueAtTime(Math.max(.001,musicMaster.gain.value),t);musicMaster.gain.linearRampToValueAtTime(Math.max(.01,Math.min(.35,target)),t+.45)}catch(e){}}return}if(musicOn)soundtrackAnimateLevel(1,450)}
const soundtrackBaseBegin=begin;begin=function(){setSoundtrack('event',1200);return soundtrackBaseBegin()};
const soundtrackBaseReset=resetSetup;resetSetup=function(){setSoundtrack('event',1400);return soundtrackBaseReset()};
const soundtrackBaseCeremony=showCeremony;showCeremony=function(player,f,done){if(state.current===state.players-1)setSoundtrack('cathedral',2600);return soundtrackBaseCeremony(player,f,done)};
const soundtrackBaseVerdict=showCouncilVerdict;showCouncilVerdict=function(result,ctx,done){setSoundtrack('cathedral',1400);return soundtrackBaseVerdict(result,ctx,done)};
soundtrackEnsureVolumeControl();soundtrackSetLabel();
