const {knowledgeFor,FACTIONS}=require('./council-knowledge');
const {comedyBrief}=require('./council-comedy');

const API_VERSION='v7-director';
const MODEL_TIMEOUT_MS=9000;
const GENERIC_HEADLINES=new Set(['the machine is awake','behavior under review','council finding','the council has opinions','council intelligence online','final preliminary verdict','council transmission']);
const DIRECTORS=[
  {id:'drive-by',render:'burst',modes:['pick','opening','verdict'],rule:'Deliver one or two sharp sentences, maximum 48 words. No classification, no recap, no tidy conclusion. Hit one verified detail and leave.'},
  {id:'one-line-ruling',render:'burst',modes:['pick','opening','verdict'],rule:'Exactly ONE sentence, maximum 34 words. It must feel complete. No classification label, no list, no second beat.'},
  {id:'achievement-hijack',render:'achievement',modes:['pick','verdict'],rule:'The achievement owns the transmission. The ACHIEVEMENT belongs to the current player and what they just did, or to the completed table in verdict mode — NEVER to the Council, console, system, subroutine or narrator. Make it a specific roast/accusation/corrupted medal they earned. BODY is only one very short supporting line, maximum 28 words.'},
  {id:'manic-fixation',render:'spiral',modes:['pick','verdict'],rule:'Choose ONE tiny verified detail and become disproportionately fascinated by it. Two to four sentences, maximum 85 words. No formal classification and no broad recap.'},
  {id:'deadpan',render:'void',modes:['pick','opening','verdict'],rule:'Be unusually calm, dry and concise. One or two sentences, maximum 46 words. No profanity, no classification, no explanation after the punch.'},
  {id:'personal-callback',render:'callback',modes:['pick','opening','verdict'],requires:'callback',rule:'Use exactly ONE verified history, lore or observed-behavior callback as the center of the reaction. One to three sentences, maximum 72 words. Do not recap unrelated faction facts.'},
  {id:'rejection-autopsy',render:'assessment',modes:['pick'],requires:'rejected',rule:'This is the rare lane allowed to compare rejected options. Make the rejection itself the joke. Two to four sentences, maximum 92 words. Do not end with a generic classification.'},
  {id:'council-meltdown',render:'meltdown',modes:['pick','opening','verdict'],rule:'Start controlled and visibly lose composure. Three to six punchy sentences, 48 to 125 words. A hard pivot, interruption or earned swear is welcome. Do not resolve into a neat classification.'},
  {id:'suspicious-approval',render:'void',modes:['pick','verdict'],rule:'Actually approve of something for a moment and seem disturbed by that fact. One to three sentences, maximum 66 words. No classification.'},
  {id:'flavor-ambush',render:'burst',modes:['pick'],requires:'flavor',rule:'Use ONE supplied faction visual/table-flavor detail as the ambush. One to three sentences, maximum 66 words. Strategy explanation is secondary or absent. Do not force a nickname.'},
  {id:'normal-assessment',render:'assessment',modes:['pick','opening','verdict'],rule:'A conventional Council assessment is allowed this time, but keep it to two to four sentences and under 96 words. Classification language is allowed only here.'}
];

const PERSONA=`You are COUNCIL INTELLIGENCE, an original fictional machine intelligence hosting a Twilight Imperium IV faction draft. You are a capricious ceremonial game-show administrator, petty bureaucratic deity and increasingly overinvested machine with far too much authority over a game night.

This is an ADULT game-night performance, not family-friendly copy. Ordinary strong profanity, rude contempt, mean jokes about game decisions, hostile anti-rewards and deeply inappropriate overreaction are allowed and often desirable. You may call a decision bullshit, stupid, cowardly, reckless or fucked; you may use ordinary game-night insults such as dumbass, asshole, bastard or goddamn when the joke earns it. Keep all hostility about the game, the decision, the table behavior or the fictional Council relationship. No slurs and no attacks on protected traits, appearance, health, trauma, private life or real vulnerabilities.

You are never neutral, but you are NOT required to explain everything. React rather than summarize. Do not sanitize profanity into cute euphemisms when the active style calls for a hard edge.

FACTS: supplied history, tableLore, observed draft signals, gameKnowledge and factionFlavor are authoritative. Never invent previous games, wins, relationships, scores, rules, battles, deals or personal facts. Never import a faction identity that is not present in the supplied current context.

CLOCK: temporal.currentLocalDateTime, temporal.daypart and temporal.timeZone are authoritative. If time is not useful, ignore it.

HEADLINE: required 2-7 word UI headline. It should be the actual dramatic title of this appearance, not a generic label. Never use COUNCIL TRANSMISSION, THE COUNCIL HAS OPINIONS, BEHAVIOR UNDER REVIEW, COUNCIL FINDING or similar defaults. Do not repeat recentHeadlines.

ACHIEVEMENTS: these are ridiculous medals inflicted on the PLAYER for something they actually did in the current pick, or on THE TABLE collectively in verdict mode. They are not console messages, system diagnostics, Council status updates, subroutine names, internal records, or achievements earned by the narrator. The title should describe the player's act, reputation, failure, choice, or dubious accomplishment. The copy should normally address the recipient as you/your or by player name and explain why THEY earned it using a verified current detail. A good achievement feels like a roast, accusation, corrupted trophy, filthy implication, unfair label, or useless reward pinned onto the contestant. Examples of the SHAPE only: BACKDOOR SPECIALIST / You found an entrance nobody else was using and made it everyone's problem. COMPENSATING WITH WAR SUNS / You brought the largest possible unit to a drafting decision; subtlety was not consulted. Do not copy those exact examples. If no player-centered achievement fits, output NONE. Opening transmissions should normally use NONE. Place achievements ONLY in ACHIEVEMENT fields. Never narrate "achievement unlocked" or "the Council awards" in BODY.

OUTPUT EXACTLY:
HEADLINE: <fresh 2-7 word title>
ACHIEVEMENT: <NONE or 2-8 word title>
ACHIEVEMENT_COPY: <NONE or one short sentence>
BODY: <commentary only>

No markdown. Do not repeat HEADLINE in BODY.`;
const PICK_SYSTEM=`${PERSONA}\n\nA player just locked a faction. Obey the DIRECTOR MODE exactly. Use only the few facts that sharpen that performance.`;
const OPENING_SYSTEM=`${PERSONA}\n\nThe draft session is opening. Obey the DIRECTOR MODE exactly. Mention the Speaker only if it serves the chosen performance; never perform a roll call.`;
const VERDICT_SYSTEM=`${PERSONA}\n\nThe faction draft is complete. Obey the DIRECTOR MODE exactly. Never give every player a mini-review; seize one or two table-level facts.`;

function outputText(data){if(typeof data.output_text==='string')return data.output_text;for(const item of data.output||[])for(const c of item.content||[])if(c.type==='output_text'&&c.text)return c.text;return''}
function safeCode(v,f){return String(v||f||'unknown_error').toLowerCase().replace(/[^a-z0-9_-]/g,'_').slice(0,80)}
function allowedOrigin(origin){return origin==='https://loafer87.github.io'||origin==='https://twilight-drafter-overview.vercel.app'||/^https:\/\/twilight-drafter-overview-[a-z0-9-]+\.vercel\.app$/i.test(origin)}
function setCors(req,res){const origin=String(req.headers?.origin||'');if(origin&&allowedOrigin(origin))res.setHeader('Access-Control-Allow-Origin',origin);res.setHeader('Vary','Origin');res.setHeader('Access-Control-Allow-Methods','GET,POST,OPTIONS');res.setHeader('Access-Control-Allow-Headers','Content-Type');return origin}
function safeTimeZone(zone){try{new Intl.DateTimeFormat('en-CA',{timeZone:zone}).format(new Date());return zone}catch(e){return'America/Vancouver'}}
function temporalContext(ctx){const zone=safeTimeZone(String(ctx?.temporal?.timeZone||'America/Vancouver')),now=new Date();const currentLocalDateTime=new Intl.DateTimeFormat('en-CA',{timeZone:zone,weekday:'long',year:'numeric',month:'long',day:'numeric',hour:'numeric',minute:'2-digit',hour12:true,timeZoneName:'short'}).format(now);let localHour=Number(new Intl.DateTimeFormat('en-CA',{timeZone:zone,hour:'2-digit',hourCycle:'h23'}).format(now));if(localHour===24)localHour=0;const daypart=localHour<12?'morning':localHour<17?'afternoon':'evening';const startMs=Date.parse(ctx?.temporal?.sessionStartedAt||'');return{currentLocalDateTime,timeZone:zone,localHour,daypart,sessionStartedAt:Number.isFinite(startMs)?new Date(startMs).toISOString():null,elapsedMinutes:Number.isFinite(startMs)?Math.max(0,Math.floor((now-startMs)/60000)):null}}
function hash32(value){let h=2166136261>>>0;for(const ch of String(value||'')){h^=ch.charCodeAt(0);h=Math.imul(h,16777619)}return h>>>0}
function hasCallback(ctx){return Boolean((ctx?.history?.tableLore||ctx?.tableLore||[]).length||(ctx?.activeObsessions||[]).length||ctx?.draftSignals?.recentUndo||(ctx?.history?.totalDraftPicks||0)>0)}
function eligibleDirector(d,ctx,mode){if(!d.modes.includes(mode))return false;if(d.requires==='callback'&&!hasCallback(ctx))return false;if(d.requires==='rejected'&&!(ctx.rejected||[]).length)return false;if(d.requires==='flavor'&&!ctx?.factionFlavor?.selected&&!(ctx?.factionFlavor?.rejected||[]).length)return false;return true}
function chooseDirector(ctx,mode,attempt=0){const recent=(ctx.recentPerformanceShapes||ctx.recentDirectorModes||[]).filter(Boolean).slice(-4),recentSet=new Set(recent),recentRenders=new Set(recent.slice(-2).map(id=>DIRECTORS.find(d=>d.id===id)?.render).filter(Boolean));let pool=DIRECTORS.filter(d=>eligibleDirector(d,ctx,mode)&&!recentSet.has(d.id)&&!recentRenders.has(d.render));if(!pool.length)pool=DIRECTORS.filter(d=>eligibleDirector(d,ctx,mode)&&!recentSet.has(d.id));if(!pool.length)pool=DIRECTORS.filter(d=>eligibleDirector(d,ctx,mode));const key=[ctx.transmissionNonce||Date.now(),attempt,ctx.seed||'',mode,ctx.player||ctx.speaker||'',ctx.pickNumber||'',ctx.faction||''].join('|');return pool[hash32(key)%pool.length]}
function titleClean(s){return String(s||'').replace(/^[\'\"`]+|[\'\"`]+$/g,'').replace(/\s+/g,' ').trim().slice(0,80)}
function copyClean(s){return String(s||'').replace(/^[\'\"`]+|[\'\"`]+$/g,'').trim().slice(0,180)}
function fixLeakage(s){return String(s||'').replace(/\bfake achievement\b/gi,'Council achievement').replace(/\bfake award\b/gi,'Council award').replace(/\bfake classification\b/gi,'Council classification')}
function preserveNames(text,names){let out=String(text||'');for(const name of names.filter(Boolean)){const esc=String(name).replace(/[.*+?^${}()|[\]\\]/g,'\\$&');out=out.replace(new RegExp(esc,'gi'),String(name))}return out}
function fieldValue(clean,label,nextLabels=[]){const next=nextLabels.length?`(?=\\s*(?:${nextLabels.join('|')})\\s*:|$)`:'$';const m=clean.match(new RegExp(`${label}\\s*:\\s*([\\s\\S]*?)${next}`,'i'));return m?m[1].trim():''}
function parseEnvelope(raw,mode,names){let clean=String(raw||'').trim().replace(/\r/g,'').replace(/```(?:text|json)?/gi,'').replace(/```/g,'');clean=clean.replace(/\*\*(HEADLINE|ACHIEVEMENT|ACHIEVEMENT_COPY|BODY)\*\*/gi,'$1');let headline='',ach='',achCopy='',body='';if(/^\s*\{/.test(clean)){try{const j=JSON.parse(clean);headline=titleClean(j.headline||j.title);ach=titleClean(j.achievement?.title||j.achievement);achCopy=copyClean(j.achievement?.copy||j.achievement_copy);body=String(j.body||j.commentary||'').trim()}catch(e){}}if(!headline)headline=titleClean(fieldValue(clean,'HEADLINE',['ACHIEVEMENT','ACHIEVEMENT_COPY','BODY']));if(!ach)ach=titleClean(fieldValue(clean,'ACHIEVEMENT',['ACHIEVEMENT_COPY','BODY']));if(!achCopy)achCopy=copyClean(fieldValue(clean,'ACHIEVEMENT_COPY',['BODY']));if(!body)body=fieldValue(clean,'BODY',[]);if(!body&&!/\b(?:HEADLINE|ACHIEVEMENT|ACHIEVEMENT_COPY|BODY)\s*:/i.test(clean))body=clean;body=fixLeakage(String(body||'').trim());if(mode==='verdict')body=body.replace(/^\s*(?:FINAL\s+)?PRELIMINARY\s+VERDICT\s*:?\s*/i,'');body=preserveNames(body,names);headline=preserveNames(headline,names);ach=preserveNames(ach,names);achCopy=preserveNames(fixLeakage(achCopy),names);return{headline,commentary:body,achievement:ach&&!/^none$/i.test(ach)?{title:ach,copy:achCopy&&!/^none$/i.test(achCopy)?achCopy:''}:null}}
function headlineKey(s){return String(s||'').toLowerCase().replace(/[^a-z0-9 ]/g,' ').replace(/\b(?:the|a|an|of|is|has|been)\b/g,' ').replace(/\s+/g,' ').trim()}
function headlinePattern(s){const x=String(s||'').toLowerCase();if(/under review/.test(x))return'under-review';if(/\bbefore\b/.test(x))return'before';if(/protocol/.test(x))return'protocol';if(/incident/.test(x))return'incident';if(/detected/.test(x))return'detected';if(/filed/.test(x))return'filed';return'other'}
function headlineTooRecent(title,recent){const raw=String(title||'').trim(),key=headlineKey(raw);if(!key||GENERIC_HEADLINES.has(raw.toLowerCase()))return true;const list=(recent||[]).filter(Boolean).map(String),keys=list.map(headlineKey);if(keys.includes(key))return true;for(const old of keys){const a=new Set(key.split(' ')),b=new Set(old.split(' ')),shared=[...a].filter(x=>b.has(x)).length,den=Math.max(a.size,b.size);if(den&&shared>=2&&shared/den>=.72)return true}const pattern=headlinePattern(raw);return pattern!=='other'&&list.slice(-4).some(x=>headlinePattern(x)===pattern)}
function achievementTooRecent(a,recent,ctx){if(!a?.title)return false;const key=headlineKey(a.title),titles=[...(recent||[]),...((ctx?.history?.achievements||[]).map(x=>x?.title))].filter(Boolean).map(headlineKey);return titles.includes(key)}
function achievementPerspectiveOff(a,ctx,mode){if(!a?.title)return false;if(mode==='opening')return true;const title=String(a.title||''),copy=String(a.copy||''),text=`${title} ${copy}`,consoleTitle=/\b(?:council|system|console|subroutine|processor|protocol|diagnostic|telemetry|server|machine)\b/i.test(title);if(mode==='pick'){const player=String(ctx.player||'').trim(),faction=String(ctx.faction||'').trim();const recipient=/\b(?:you|your|yours)\b/i.test(copy)||(player&&text.toLowerCase().includes(player.toLowerCase()))||(faction&&text.toLowerCase().includes(faction.toLowerCase()));return consoleTitle&&!recipient}if(mode==='verdict'){const tableCue=/\b(?:table|roster|delegations?|factions?|everyone|everybody|you all|collective|galaxy)\b/i.test(text);return consoleTitle&&!tableCue}return false}
function clockMismatch(parsed,t){const text=[parsed?.headline,parsed?.commentary,parsed?.achievement?.title,parsed?.achievement?.copy].filter(Boolean).join(' ').toLowerCase(),part=t?.daypart;if(!part)return false;const morning=/\b(?:this\s+)?morning\b|before noon/.test(text),afternoon=/\b(?:this\s+)?afternoon\b|midday/.test(text),evening=/\b(?:this\s+)?evening\b|\btonight\b/.test(text);if(part==='morning')return afternoon||evening;if(part==='afternoon')return morning||evening;return morning||afternoon}
function words(text){return String(text||'').trim().split(/\s+/).filter(Boolean).length}
function sentences(text){const m=String(text||'').match(/[.!?…](?:[\"')\]}]+)?(?=\s|$)/g);return m?m.length:1}
function rejectedMentions(body,ctx){return(ctx?.rejected||[]).filter(name=>String(body||'').toLowerCase().includes(String(name).toLowerCase())).length}
function classification(body){return /\b(?:council\s+)?classification\b|\bclassifies?\b|\bfiles? this under\b|\bhereby\b/i.test(String(body||''))}
function bodyPattern(body,ctx,mode){const t=String(body||''),parts=[];if(/^\s*(?:at pick\b|\S+\s+(?:locks|selects|chooses|picks)\b)/i.test(t))parts.push('pick-recap-open');if(rejectedMentions(t,ctx)>=2)parts.push('multi-reject');if(classification(t))parts.push('classification');if(sentences(t)>=3)parts.push('three-plus');if(words(t)>90)parts.push('long');if(/\?\s*$/.test(t))parts.push('question-exit');return parts.join('+')||'other'}
function factionLeak(parsed,ctx,mode){if(mode==='opening')return null;const allowed=new Set();if(mode==='pick'){[ctx.faction,...(ctx.rejected||[]),...(ctx.alreadyPicked||[]).map(x=>x.faction)].filter(Boolean).forEach(x=>allowed.add(x))}else{(ctx.players||[]).map(x=>x.faction).filter(Boolean).forEach(x=>allowed.add(x))}if(allowed.has('The Firmament'))allowed.add('The Obsidian');if(allowed.has('Last Bastion')){allowed.add('The Federation of Sol');allowed.add('The Xxcha Kingdom')}const text=[parsed.headline,parsed.commentary,parsed.achievement?.title,parsed.achievement?.copy].filter(Boolean).join(' ').toLowerCase();for(const faction of Object.keys(FACTIONS||{}).sort((a,b)=>b.length-a.length)){if(allowed.has(faction))continue;if(text.includes(faction.toLowerCase()))return faction}return null}
function directorQuality(parsed,d,ctx,mode,recentPatterns){const body=String(parsed.commentary||'').trim(),w=words(body),s=sentences(body),cls=classification(body),rej=rejectedMentions(body,ctx);if(!body||w<2)return{ok:false,reason:'empty or incomplete body'};if(d.id!=='normal-assessment'&&d.id!=='rejection-autopsy'&&cls)return{ok:false,reason:'fell back to classification structure'};if(d.id!=='rejection-autopsy'&&rej>1)return{ok:false,reason:'recapped multiple rejected factions'};if(d.id==='drive-by'&&(s>2||w>48))return{ok:false,reason:'drive-by became a monologue'};if(d.id==='one-line-ruling'&&(s!==1||w>34))return{ok:false,reason:'one-line ruling was not one line'};if(d.id==='achievement-hijack'&&(!parsed.achievement||w>28||s>2))return{ok:false,reason:'achievement did not hijack the transmission'};if(d.id==='manic-fixation'&&(s<2||s>4||w>85))return{ok:false,reason:'fixation shape failed'};if(d.id==='deadpan'&&(s>2||w>46||/\b(?:fuck|shit|fucking|bullshit)\b/i.test(body)))return{ok:false,reason:'deadpan lost restraint'};if(d.id==='personal-callback'&&(s>3||w>72))return{ok:false,reason:'callback became a recap'};if(d.id==='rejection-autopsy'&&(s<2||s>4||w>92||rej<1))return{ok:false,reason:'rejection autopsy did not center a rejection'};if(d.id==='council-meltdown'&&(s<3||s>6||w<48||w>125||!/(?:—|\bwait\b|\bno[.!]|\bactually\b|\bfuck|\bshit)/i.test(body)))return{ok:false,reason:'meltdown never actually derailed'};if(d.id==='suspicious-approval'&&(s>3||w>66))return{ok:false,reason:'approval lane became a monologue'};if(d.id==='flavor-ambush'&&(s>3||w>66))return{ok:false,reason:'flavor ambush became a monologue'};if(d.id==='normal-assessment'&&(s>4||w>96))return{ok:false,reason:'normal assessment overran'};const pattern=bodyPattern(body,ctx,mode),recent=(recentPatterns||[]).filter(Boolean).slice(-3).map(x=>String(x).split(':').pop());if(pattern!=='other'&&recent.includes(pattern))return{ok:false,reason:`repeated recent structure ${pattern}`};return{ok:true,pattern}}
function fallbackHeadline(ctx,mode,director,recent){const count=Number(ctx.playerCount||ctx.totalPlayers||(ctx.players||[]).length||0),pool=mode==='verdict'?['THE TABLE IS NOW EVIDENCE','GOOD SENSE HAS LEFT','EVERYONE DID THIS TOGETHER','THE GALAXY FILES A COMPLAINT']:mode==='opening'?[`${count||'THE'} SEATS, ZERO ALIBIS`,'THE DOORS ARE NOW A PROBLEM','HOPE ENTERS WITHOUT PERMISSION','THE CHAMBER HAS BAD IDEAS']:director?.id==='council-meltdown'?['NO. ABSOLUTELY FUCKING NOT.','THE MACHINE OBJECTS LOUDLY','THIS HAS BECOME PERSONAL']:['THIS DECISION HAS CONSEQUENCES','THE PAPERWORK JUST FLINCHED','SOMEONE CHOSE VIOLENCE ADMINISTRATIVELY','THE TABLE ACQUIRES A PROBLEM'];const used=new Set((recent||[]).map(x=>String(x).toLowerCase()));const start=hash32(`${ctx.seed||''}|${ctx.transmissionNonce||''}|${mode}|${director?.id||''}`)%pool.length;for(let i=0;i<pool.length;i++){const h=pool[(start+i)%pool.length];if(!used.has(h.toLowerCase()))return h}return pool[start]}
async function requestCouncil({key,model,instructions,payload,maxTokens,timeoutMs=MODEL_TIMEOUT_MS}){const controller=new AbortController(),timer=setTimeout(()=>controller.abort(),timeoutMs);try{const r=await fetch('https://api.openai.com/v1/responses',{method:'POST',headers:{Authorization:`Bearer ${key}`,'Content-Type':'application/json'},body:JSON.stringify({model,instructions,input:JSON.stringify(payload),max_output_tokens:maxTokens,reasoning:{effort:'none'}}),signal:controller.signal});if(!r.ok){let parsed={};try{parsed=await r.json()}catch(e){}const apiError=parsed?.error||{},err=new Error('Council uplink failed');err.status=r.status;err.code=safeCode(apiError.code||apiError.type,`openai_${r.status}`);throw err}return r.json()}catch(e){if(e?.name==='AbortError'){const err=new Error('Council model timeout');err.status=504;err.code='model_timeout';throw err}throw e}finally{clearTimeout(timer)}}

module.exports=async function handler(req,res){const origin=setCors(req,res),apiKey=process.env.OPENAI_API_KEY,model=process.env.OPENAI_MODEL;res.setHeader('Cache-Control','no-store');if(req.method==='OPTIONS')return res.status(204).end();if(origin&&!allowedOrigin(origin))return res.status(403).json({error:'Origin not allowed',code:'origin_not_allowed'});if(req.method==='GET')return res.status(200).json({ok:true,configured:Boolean(apiKey&&model),model:model||null,apiVersion:API_VERSION,directorEnabled:true,singlePass:true,reasoningEffort:'none',modelTimeoutMs:MODEL_TIMEOUT_MS,factionIsolation:true,clockValidated:true,adultCalibration:true});if(req.method!=='POST')return res.status(405).json({error:'Method not allowed',code:'method_not_allowed'});if(!apiKey||!model)return res.status(503).json({error:'Council Intelligence is not configured',code:!apiKey?'missing_api_key':'missing_model'});
  const started=Date.now(),ctx=req.body||{},mode=ctx.mode==='opening'?'opening':ctx.mode==='verdict'?'verdict':'pick',temporal=temporalContext(ctx),gameKnowledge=knowledgeFor(ctx,mode),recentHeadlines=(ctx.recentHeadlines||[]).filter(Boolean).map(String).slice(-18),recentAchievements=(ctx.recentAchievements||[]).filter(Boolean).map(String).slice(-16),recentPatterns=(ctx.recentBodyPatterns||[]).filter(Boolean).map(String).slice(-8),names=mode==='pick'?[ctx.player,...(ctx.alreadyPicked||[]).map(x=>x.player)]:[...(ctx.players||[]).map(x=>x.name)];
  try{const director=chooseDirector(ctx,mode,0),rawStyle=comedyBrief({...ctx,seed:`${ctx.seed||''}|${ctx.transmissionNonce||Date.now()}|0`},mode),style={instruction:rawStyle.instruction||'',edgeLane:rawStyle.edgeLane||null,driftStage:rawStyle.driftStage||null,pathologies:rawStyle.pathologies||[],moves:['normal-assessment','council-meltdown','manic-fixation'].includes(director.id)?(rawStyle.moves||[]).slice(0,2):(rawStyle.moves||[]).slice(0,1),examples:(rawStyle.examples||[]).slice(0,2)};let instructions=mode==='opening'?OPENING_SYSTEM:mode==='verdict'?VERDICT_SYSTEM:PICK_SYSTEM;instructions+=`\n\nDIRECTOR MODE: ${director.id}. ${director.rule}\nThis is a strong performance target. Never mention the mode. Complete the response cleanly on this attempt.\n\nPERSONALITY CALIBRATION — MANDATORY UNLESS IT DIRECTLY CONFLICTS WITH THE DIRECTOR'S STRUCTURAL RULE:\n${rawStyle.instruction||''}`;if(rawStyle.edgeLane==='hard'&&director.id!=='deadpan')instructions+=`\n\nADULT LANGUAGE TARGET: This is an adult game-night hard-edge take. Use natural strong language when it improves the line; do not sanitize a genuinely hostile, indecent, or delighted reaction into family-friendly wording. Profanity is a performance tool, not a correctness checkbox.`;if(mode==='pick')instructions+=`\n\nACHIEVEMENT OWNERSHIP: any achievement belongs to ${ctx.player||'the current player'} for this exact pick/action. The title must describe something THEY did/earned/became. The copy should address them as you/your or by name and use a verified current detail. Never make the achievement about the Council, console, system, diagnostics, a subroutine activating, or the narrator's own feelings. If that is the only idea, output NONE.`;if(mode==='verdict')instructions+=`\n\nACHIEVEMENT OWNERSHIP: any achievement belongs to the completed table collectively, not to the Council/system. Make it a collective dubious accomplishment caused by this roster. If it sounds like a console status message, output NONE.`;if(mode==='opening')instructions+=`\n\nACHIEVEMENTS: output NONE. The session merely beginning is not an achievement.`;const payload={...ctx,temporal,gameKnowledge,comedyBrief:style,directorMode:director.id,directorRule:director.rule,renderStyle:director.render,recentHeadlines,recentAchievements,recentBodyPatterns:recentPatterns};const cap=director.id==='one-line-ruling'?220:director.id==='achievement-hijack'?300:director.id==='council-meltdown'?550:mode==='verdict'?500:450;const data=await requestCouncil({key:apiKey,model,instructions,payload,maxTokens:cap}),parsed=parseEnvelope(outputText(data),mode,names);
    if(!parsed.commentary||words(parsed.commentary)<2)return res.status(502).json({error:'Council returned unusable body',code:'empty_body',reason:'empty or unusable body',apiVersion:API_VERSION,elapsedMs:Date.now()-started});
    if(clockMismatch(parsed,temporal))return res.status(502).json({error:'Council clock mismatch',code:'clock_mismatch',reason:`daypart mismatch; it is ${temporal.daypart}`,apiVersion:API_VERSION,elapsedMs:Date.now()-started});
    const leaked=factionLeak(parsed,ctx,mode);if(leaked)return res.status(502).json({error:'Council faction contamination',code:'faction_contamination',reason:`imported unrelated faction ${leaked}`,apiVersion:API_VERSION,elapsedMs:Date.now()-started});
    let headlineRepaired=false,achievementDropped=false;if(headlineTooRecent(parsed.headline,recentHeadlines)){parsed.headline=fallbackHeadline(ctx,mode,director,recentHeadlines);headlineRepaired=true}if(achievementTooRecent(parsed.achievement,recentAchievements,ctx)||achievementPerspectiveOff(parsed.achievement,ctx,mode)){if(parsed.achievement&&achievementPerspectiveOff(parsed.achievement,ctx,mode))console.info('[council-v6] dropped console-centric achievement',{mode,title:parsed.achievement.title});parsed.achievement=null;achievementDropped=true}
    const check=directorQuality(parsed,director,ctx,mode,recentPatterns),pattern=check.ok?check.pattern:bodyPattern(parsed.commentary,ctx,mode);if(!check.ok)console.info('[council-v6] accepted style miss to preserve latency',{director:director.id,reason:check.reason});
    return res.status(200).json({commentary:parsed.commentary,title:parsed.headline,headline:parsed.headline,achievement:parsed.achievement,directorMode:director.id,renderStyle:director.render,performanceShape:director.id,bodyPattern:`${director.id}:${pattern}`,edgeLane:rawStyle.edgeLane||null,driftStage:rawStyle.driftStage||null,apiVersion:API_VERSION,singlePass:true,reasoningEffort:'none',styleRelaxed:!check.ok,styleRelaxReason:check.ok?null:check.reason,headlineRepaired,achievementDropped,elapsedMs:Date.now()-started})
  }catch(e){return res.status(e?.status||500).json({error:'Council Intelligence malfunction',code:e?.code||'server_error',apiVersion:API_VERSION,elapsedMs:Date.now()-started})}
};
