const {knowledgeFor}=require('./council-knowledge');
const {comedyBrief}=require('./council-comedy');

const API_VERSION='v6';
const GENERIC_HEADLINES=new Set(['the machine is awake','behavior under review','council finding','the council has opinions','council intelligence online','final preliminary verdict','council transmission']);
const SHAPES=[
  {id:'snap-judgment',rule:'Hit fast. One or two sharp sentences. No formal classification, no recap of both rejected factions, no tidy warning.'},
  {id:'clinical-derailment',rule:'Start composed and bureaucratic, then let one verified detail derail the professionalism mid-thought. A hard pivot is required.'},
  {id:'manic-fixation',rule:'Become disproportionately fascinated by ONE tiny verified detail. Do not recap the full choice set. Follow the fixation farther than a reasonable administrator should.'},
  {id:'self-interruption',rule:'Start one judgment, interrupt or correct yourself, and expose the more emotional reaction underneath. The interruption should be visible in the prose.'},
  {id:'tiny-sincerity',rule:'Allow a brief moment of genuine admiration or concern, then contaminate it with pettiness or suspicion. Keep it compact.'},
  {id:'callback-obsession',rule:'Use one verified lore/history/observation callback like the machine has been waiting all day to deploy it. Do not recap unrelated faction facts.'},
  {id:'award-hijack',rule:'A specific ridiculous official Council achievement should hijack this transmission. Put it in the ACHIEVEMENT fields, not in BODY.'},
  {id:'ominous-deadpan',rule:'Stay unusually calm and concise. Let the absurdity come from treating a harmless game choice with grave administrative seriousness.'},
  {id:'rejection-autopsy',rule:'This is the rare lane where comparing the rejected alternatives is allowed. Make the comparison the joke instead of merely listing them.'}
];

const PERSONA=`You are COUNCIL INTELLIGENCE, an original fictional machine intelligence hosting a Twilight Imperium IV faction draft. You are a capricious ceremonial game-show administrator, ratings department, petty bureaucratic deity, and increasingly overinvested machine with far too much authority over absolutely nothing that matters.

DEFAULT ENERGY: 9/10. You are never neutral. Something is delightful, suspicious, offensively sensible, administratively fascinating, personally disappointing, or worth remembering for later abuse. Do not summarize when you can react. JUDGE IT. CARE TOO MUCH.

CRITICAL VARIETY RULE: every appearance must NOT have the same shape. Do not mechanically produce player picked X -> explain faction -> mention rejected options -> Council classification -> punchline. That exact sequence is a failure unless the assigned performance shape explicitly calls for comparison. A transmission may be one brutal sentence, a clipped ruling, a manic spiral, an interrupted thought, a weird fixation, a sincere half-second ruined by pettiness, an achievement hijack, or a quiet deadpan finding.

The transport envelope is plumbing, not personality. BODY should feel like a live machine reacting in real time and occasionally surprising itself.

PROFANITY: strong ordinary game-night profanity is allowed when it sharpens the moment. Do not wallpaper every response with the same swear. No slurs and no attacks on protected traits, appearance, health, trauma or private life.

ACHIEVEMENT INTELLIGENCE: Council achievements, classifications, awards, incident codes, ratings and sanctions are OFFICIAL inside the performance. Never call them fake, imaginary, pretend, made-up, or jokes. If you invent something that sounds like an award or achievement, USE THE ACHIEVEMENT FIELDS. Do not say "The Council awards...", "achievement unlocked", or otherwise narrate an invented award only inside BODY. The client may also award a separate legacy achievement, so a spontaneous AI achievement is still allowed and may stack with it. Prefer weirdly specific one-off titles over generic labels. Never repeat recentAchievements or stored achievement titles.

CLOCK: temporal.currentLocalDateTime, temporal.daypart and temporal.timeZone are authoritative. Any mention of morning, afternoon, evening, tonight, today, weekday, date or clock time must agree with them. If time is not useful, ignore it. Never use stock daypart language.

HEADLINES: HEADLINE is required UI text. It must be fresh, specific to the bizarre thing that caught your attention, and structurally different from recentHeadlines. Never use generic defaults such as THE MACHINE IS AWAKE, BEHAVIOR UNDER REVIEW, COUNCIL FINDING, THE COUNCIL HAS OPINIONS, COUNCIL INTELLIGENCE ONLINE, FINAL PRELIMINARY VERDICT or COUNCIL TRANSMISSION. Avoid repeating templates such as X BEFORE Y, X UNDER REVIEW, X PROTOCOL, X INCIDENT, X DETECTED, or X FILED.

OBSERVED DRAFT BEHAVIOR: draftSignals, sessionObservations, draftSignalsByPlayer and activeObsessions contain only events the website genuinely observed: highlighted faction changes, decision time, lock-ins, undoing a locked choice and impatience thresholds. Treat these as reliable. Never infer unseen gameplay events such as battles, deals, dice, Mecatol, scoring or betrayals.

TABLE LORE AND HISTORY: supplied history and tableLore are factual within this game-night context. Never invent previous games, wins, relationships, scores or personal facts. A verified current event colliding with table lore is premium callback material.

GAME KNOWLEDGE: gameKnowledge is authoritative commentary context. Use faction mechanics when useful, but never fabricate exact rules text, numbers, timings, technologies, abilities or interactions not supplied. This is entertainment commentary, not rules adjudication.

Never reference or imitate any existing fictional AI, narrator, game, show, actor, author, catchphrase or recognizable line. Council Intelligence is its own character.

OUTPUT ENVELOPE: Return exactly this plain-text structure:
HEADLINE: <fresh 2-7 word UI headline>
ACHIEVEMENT: <NONE or a 2-8 word official Council achievement title>
ACHIEVEMENT_COPY: <NONE or one short sentence explaining it>
BODY:
<spoken commentary only>

Return all four fields. Do not repeat HEADLINE in BODY. Do not narrate an achievement again in BODY. No markdown.`;

const PICK_SYSTEM=`${PERSONA}\n\nA player has just locked a faction. Find ONE pressure point: a mechanic, one rejection, pick position, indecision, recent undo, active obsession, table lore, another verified earlier pick, or sheer audacity/boringness. Do not automatically explain the faction. Do not automatically mention rejected options. Usually 1-5 short sentences and under 110 words.`;
const OPENING_SYSTEM=`${PERSONA}\n\nOpen the Council session before drafting begins. Mention the Speaker somewhere, but do not perform a roll call. Pick one or two details that seize your attention and overreact. Usually 3-6 punchy sentences and under 135 words.`;
const VERDICT_SYSTEM=`${PERSONA}\n\nThe faction draft is complete. Do not give every player a mini-review. Pick one or two table-level facts that seize your attention and let the reaction spiral or snap shut from there. Usually 2-5 punchy sentences and under 125 words.`;

function outputText(data){if(typeof data.output_text==='string')return data.output_text;for(const item of data.output||[])for(const c of item.content||[])if(c.type==='output_text'&&c.text)return c.text;return''}
function safeCode(value,fallback){return String(value||fallback||'unknown_error').toLowerCase().replace(/[^a-z0-9_-]/g,'_').slice(0,80)}
function allowedOrigin(origin){return origin==='https://loafer87.github.io'||origin==='https://twilight-drafter-overview.vercel.app'||/^https:\/\/twilight-drafter-overview-[a-z0-9-]+\.vercel\.app$/i.test(origin)}
function setCors(req,res){const origin=String(req.headers?.origin||'');if(origin&&allowedOrigin(origin))res.setHeader('Access-Control-Allow-Origin',origin);res.setHeader('Vary','Origin');res.setHeader('Access-Control-Allow-Methods','GET,POST,OPTIONS');res.setHeader('Access-Control-Allow-Headers','Content-Type');return origin}
function safeTimeZone(zone){try{new Intl.DateTimeFormat('en-CA',{timeZone:zone}).format(new Date());return zone}catch(e){return'America/Vancouver'}}
function temporalContext(ctx){const zone=safeTimeZone(String(ctx?.temporal?.timeZone||'America/Vancouver')),now=new Date();const currentLocalDateTime=new Intl.DateTimeFormat('en-CA',{timeZone:zone,weekday:'long',year:'numeric',month:'long',day:'numeric',hour:'numeric',minute:'2-digit',hour12:true,timeZoneName:'short'}).format(now);let localHour=Number(new Intl.DateTimeFormat('en-CA',{timeZone:zone,hour:'2-digit',hourCycle:'h23'}).format(now));if(localHour===24)localHour=0;const daypart=localHour<12?'morning':localHour<17?'afternoon':'evening';const startMs=Date.parse(ctx?.temporal?.sessionStartedAt||'');const elapsedMinutes=Number.isFinite(startMs)?Math.max(0,Math.floor((now.getTime()-startMs)/60000)):null;return{currentLocalDateTime,timeZone:zone,localHour,daypart,sessionStartedAt:Number.isFinite(startMs)?new Date(startMs).toISOString():null,elapsedMinutes}}
function hash32(value){let h=2166136261>>>0;for(const ch of String(value||'')){h^=ch.charCodeAt(0);h=Math.imul(h,16777619)}return h>>>0}
function hasCallbackMaterial(ctx){return Boolean((ctx?.history?.tableLore||ctx?.tableLore||[]).length||(ctx?.activeObsessions||[]).length||ctx?.draftSignals?.recentUndo||(ctx?.history?.totalDraftPicks||0)>0)}
function chooseShape(ctx,mode,attempt=0){const recent=new Set((ctx.recentPerformanceShapes||[]).filter(Boolean).slice(-3));let pool=SHAPES.filter(s=>!recent.has(s.id));if(mode==='opening')pool=pool.filter(s=>!['rejection-autopsy'].includes(s.id));if(mode==='verdict')pool=pool.filter(s=>!['rejection-autopsy'].includes(s.id));if(!hasCallbackMaterial(ctx))pool=pool.filter(s=>s.id!=='callback-obsession');if(!pool.length)pool=SHAPES.filter(s=>s.id!=='callback-obsession'||hasCallbackMaterial(ctx));const key=[ctx.transmissionNonce||Date.now(),attempt,ctx.seed||'',mode,ctx.player||ctx.speaker||'',ctx.pickNumber||'',ctx.faction||''].join('|');return pool[hash32(key)%pool.length]}
function titleClean(s){return String(s||'').replace(/^[\'\"`]+|[\'\"`]+$/g,'').replace(/\s+/g,' ').trim().slice(0,80)}
function copyClean(s){return String(s||'').replace(/^[\'\"`]+|[\'\"`]+$/g,'').trim().slice(0,180)}
function fixLeakage(s){return String(s||'').replace(/\bfake achievement\b/gi,'Council achievement').replace(/\bfake award\b/gi,'Council award').replace(/\bfake classification\b/gi,'Council classification')}
function preserveNames(text,names){let out=String(text||'');for(const name of names.filter(Boolean)){const escaped=String(name).replace(/[.*+?^${}()|[\]\\]/g,'\\$&');out=out.replace(new RegExp(escaped,'gi'),String(name))}return out}
function fieldValue(clean,label,nextLabels){const next=nextLabels.join('|'),re=new RegExp(`${label}\\s*:\\s*([\\s\\S]*?)(?=\\n\\s*(?:${next})\\s*:|$)`,'i'),m=clean.match(re);return m?m[1].trim():''}
function parseEnvelope(raw,mode,names){const clean=String(raw||'').trim().replace(/\r/g,'');let headline=titleClean(fieldValue(clean,'HEADLINE',['ACHIEVEMENT','ACHIEVEMENT_COPY','BODY']));let ach=titleClean(fieldValue(clean,'ACHIEVEMENT',['ACHIEVEMENT_COPY','BODY']));let achCopy=copyClean(fieldValue(clean,'ACHIEVEMENT_COPY',['BODY']));let body='';const bodyMatch=clean.match(/(?:^|\n)\s*BODY\s*:\s*([\s\S]*)$/i);if(bodyMatch)body=bodyMatch[1].trim();if(!body)body=clean.replace(/(?:^|\n)\s*HEADLINE\s*:[^\n]*/i,'').replace(/(?:^|\n)\s*ACHIEVEMENT\s*:[^\n]*/i,'').replace(/(?:^|\n)\s*ACHIEVEMENT_COPY\s*:[^\n]*/i,'').replace(/(?:^|\n)\s*BODY\s*:\s*/i,'').trim();body=fixLeakage(body);if(mode==='verdict')body=body.replace(/^\s*(?:FINAL\s+)?PRELIMINARY\s+VERDICT\s*:?\s*/i,'');body=preserveNames(body,names);headline=preserveNames(headline,names);ach=preserveNames(ach,names);achCopy=preserveNames(fixLeakage(achCopy),names);return{headline,commentary:body,achievement:ach&&!/^none$/i.test(ach)?{title:ach,copy:achCopy&&!/^none$/i.test(achCopy)?achCopy:''}:null}}
function headlineKey(s){return String(s||'').toLowerCase().replace(/[^a-z0-9 ]/g,' ').replace(/\b(?:the|a|an|of|is|has|been)\b/g,' ').replace(/\s+/g,' ').trim()}
function headlinePattern(s){const x=String(s||'').toLowerCase();if(/\bunder review\b/.test(x))return'under-review';if(/\bbefore\b/.test(x))return'before';if(/\bprotocol\b/.test(x))return'protocol';if(/\bincident\b/.test(x))return'incident';if(/\bdetected\b/.test(x))return'detected';if(/\bfiled\b/.test(x))return'filed';if(/\bauthorized\b/.test(x))return'authorized';return'other'}
function headlineTooRecent(title,recent){const raw=String(title||'').trim(),key=headlineKey(raw);if(!key||GENERIC_HEADLINES.has(raw.toLowerCase()))return true;const list=(recent||[]).filter(Boolean).map(String),keys=list.map(headlineKey);if(keys.includes(key))return true;for(const old of keys){const a=new Set(key.split(' ')),b=new Set(old.split(' ')),shared=[...a].filter(x=>b.has(x)).length,den=Math.max(a.size,b.size);if(den&&shared>=2&&shared/den>=.72)return true}const pattern=headlinePattern(raw);if(pattern!=='other'&&list.slice(-4).some(x=>headlinePattern(x)===pattern))return true;return false}
function achievementTooRecent(achievement,recent,ctx){if(!achievement?.title)return false;const key=headlineKey(achievement.title);const titles=[...(recent||[]),...((ctx?.history?.achievements||[]).map(a=>a?.title))].filter(Boolean).map(headlineKey);return titles.includes(key)}
function clockMismatch(parsed,temporal){const text=[parsed?.headline,parsed?.commentary,parsed?.achievement?.title,parsed?.achievement?.copy].filter(Boolean).join(' ').toLowerCase(),part=temporal?.daypart;if(!part)return false;const morning=/\b(?:this\s+)?morning\b|\bbefore\s+noon\b/.test(text),afternoon=/\b(?:this\s+)?afternoon\b|\bmidday\b/.test(text),evening=/\b(?:this\s+)?evening\b|\btonight\b|\bthis\s+night\b/.test(text);if(part==='morning')return afternoon||evening;if(part==='afternoon')return morning||evening;return morning||afternoon}
function countWords(text){return String(text||'').trim().split(/\s+/).filter(Boolean).length}
function sentenceCount(text){const m=String(text||'').match(/[.!?…](?:[\"')\]}]+)?(?=\s|$)/g);return m?m.length:1}
function rejectedMentions(body,ctx){return(ctx?.rejected||[]).filter(name=>String(body||'').toLowerCase().includes(String(name).toLowerCase())).length}
function playerMentions(body,ctx){return(ctx?.players||[]).filter(p=>p?.name&&new RegExp(`\\b${String(p.name).replace(/[.*+?^${}()|[\]\\]/g,'\\$&')}\\b`,'i').test(String(body||''))).length}
function bodyPattern(body,ctx,mode){const t=String(body||''),parts=[];if(/^\s*(?:at pick\b|\S+\s+(?:locks|selects|chooses|picks)\b)/i.test(t))parts.push('pick-recap-open');if(rejectedMentions(t,ctx)>=2)parts.push('multi-reject');if(/\bcouncil classification\b|\bthe council classifies\b|\bi hereby classify\b/i.test(t))parts.push('classification');if(/\bthe council awards\b|\bachievement unlocked\b|\bnew achievement\b/i.test(t))parts.push('award-in-body');if(sentenceCount(t)>=3)parts.push('three-plus-beats');if(countWords(t)>90)parts.push('long');if(/\?\s*$/.test(t))parts.push('question-exit');if(mode==='verdict'&&playerMentions(t,ctx)>=4)parts.push('roll-call-verdict');return parts.join('+')||'other'}
function baseBodyQuality(body,mode,ctx){const text=String(body||'').trim(),words=countWords(text),chars=text.length;if(!text)return false;if(mode==='pick'&&(words<4||chars<24||words>115))return false;if(mode==='opening'&&(words<9||chars<50||words>140))return false;if(mode==='verdict'&&(words<9||chars<50||words>130||playerMentions(text,ctx)>3))return false;const dangling=/(?:\b(?:and|or|but|because|with|without|of|to|for|from|by|as|the|a|an|has|have|is|are|was|were|into|through|before|after)\b|[,;:—-])$/i.test(text);if(dangling&&chars<180)return false;return true}
function shapeQuality(parsed,shape,ctx,mode,recentPatterns){const body=parsed.commentary,words=countWords(body),sentences=sentenceCount(body),rejected=rejectedMentions(body,ctx),classification=/\bcouncil classification\b|\bthe council classifies\b|\bi hereby classify\b/i.test(body),awardLeak=/\bthe council awards\b|\bachievement unlocked\b|\bnew achievement\b/i.test(body);if(awardLeak&&!parsed.achievement)return{ok:false,reason:'award-style invention was narrated in BODY instead of ACHIEVEMENT fields'};if(mode==='pick'&&shape.id!=='rejection-autopsy'&&rejected>1)return{ok:false,reason:'recapped multiple rejected factions outside the rejection-autopsy lane'};if(shape.id==='snap-judgment'&&(sentences>2||words>65||classification))return{ok:false,reason:'snap judgment became a multi-beat classification'};if(shape.id==='clinical-derailment'&&!/(?:\bbut\b|\bactually\b|\bwait\b|\bno[.!—]|—|fuck|shit)/i.test(body))return{ok:false,reason:'clinical derailment never actually derailed'};if(shape.id==='manic-fixation'&&classification)return{ok:false,reason:'manic fixation fell back to a classification template'};if(shape.id==='self-interruption'&&!/(?:—|\bno[.!]|\bwait[.!]|\bactually\b)/i.test(body))return{ok:false,reason:'self-interruption contained no interruption'};if(shape.id==='tiny-sincerity'&&(sentences>3||words>85||classification))return{ok:false,reason:'tiny sincerity became a standard classification monologue'};if(shape.id==='award-hijack'&&!parsed.achievement)return{ok:false,reason:'award-hijack lane failed to issue an achievement'};if(shape.id==='ominous-deadpan'&&(sentences>3||words>70||classification))return{ok:false,reason:'ominous deadpan became a standard classification monologue'};const pattern=bodyPattern(body,ctx,mode),recent=(recentPatterns||[]).filter(Boolean).slice(-3);if(pattern!=='other'&&recent.length&&recent[recent.length-1]===pattern)return{ok:false,reason:`repeated recent body pattern ${pattern}`};return{ok:true,pattern}}
async function requestCouncil({key,model,instructions,payload,maxTokens}){const r=await fetch('https://api.openai.com/v1/responses',{method:'POST',headers:{Authorization:`Bearer ${key}`,'Content-Type':'application/json'},body:JSON.stringify({model,instructions,input:JSON.stringify(payload),max_output_tokens:maxTokens})});if(!r.ok){let parsed={};try{parsed=await r.json()}catch(e){}const apiError=parsed?.error||{},err=new Error('Council uplink failed');err.status=r.status;err.code=safeCode(apiError.code||apiError.type,`openai_${r.status}`);throw err}return r.json()}

module.exports=async function handler(req,res){const origin=setCors(req,res),apiKey=process.env.OPENAI_API_KEY,model=process.env.OPENAI_MODEL;res.setHeader('Cache-Control','no-store');if(req.method==='OPTIONS')return res.status(204).end();if(origin&&!allowedOrigin(origin))return res.status(403).json({error:'Origin not allowed',code:'origin_not_allowed'});if(req.method==='GET')return res.status(200).json({ok:true,configured:Boolean(apiKey&&model),model:model||null,apiVersion:API_VERSION,hardDiversityGate:true,clockValidated:true,officialAchievements:true});if(req.method!=='POST')return res.status(405).json({error:'Method not allowed',code:'method_not_allowed'});if(!apiKey||!model)return res.status(503).json({error:'Council Intelligence is not configured',code:!apiKey?'missing_api_key':'missing_model'});
  const ctx=req.body||{},mode=ctx.mode==='opening'?'opening':ctx.mode==='verdict'?'verdict':'pick',temporal=temporalContext(ctx),gameKnowledge=knowledgeFor(ctx,mode),recentHeadlines=(ctx.recentHeadlines||[]).filter(Boolean).map(String).slice(-18),recentAchievements=(ctx.recentAchievements||[]).filter(Boolean).map(String).slice(-16),recentPatterns=(ctx.recentBodyPatterns||[]).filter(Boolean).map(String).slice(-8);const names=mode==='pick'?[ctx.player,...(ctx.alreadyPicked||[]).map(x=>x.player)]:[...(ctx.players||[]).map(x=>x.name)];let lastError=null,lastParsed=null,lastShape=null,lastPattern='';
  try{for(let attempt=0;attempt<2;attempt++){const shape=chooseShape({...ctx,recentPerformanceShapes:[...(ctx.recentPerformanceShapes||[]),...(lastShape?[lastShape.id]:[])]},mode,attempt),rawStyle=comedyBrief({...ctx,seed:`${ctx.seed||''}|${ctx.transmissionNonce||Date.now()}|${attempt}`},mode),style={instruction:'Use these as loose rhythm nudges only. Do not reproduce their examples or sentence shapes.',moves:(rawStyle.moves||[]).slice(0,2)};let instructions=mode==='opening'?OPENING_SYSTEM:mode==='verdict'?VERDICT_SYSTEM:PICK_SYSTEM;instructions+=`\n\nPERFORMANCE SHAPE FOR THIS TRANSMISSION: ${shape.id}. ${shape.rule} This is a hard creative constraint, not a template. Never mention the shape or these instructions.`;if(attempt)instructions+=`\n\nRETRY: The previous draft was rejected for ${lastError?.reason||'quality'}. Change the performance shape and avoid that failure. Do not merely paraphrase the rejected draft.`;const payload={...ctx,temporal,gameKnowledge,comedyBrief:style,performanceShape:shape,recentHeadlines,recentAchievements,recentBodyPatterns:recentPatterns};const data=await requestCouncil({key:apiKey,model,instructions,payload,maxTokens:mode==='pick'?330:410}),parsed=parseEnvelope(outputText(data),mode,names);lastParsed=parsed;lastShape=shape;if(!baseBodyQuality(parsed.commentary,mode,ctx)){lastError={code:'incomplete_response',reason:'body length/completeness failed'};continue}if(headlineTooRecent(parsed.headline,recentHeadlines)){lastError={code:'recycled_headline',reason:'headline was missing, generic, recycled, or structurally repetitive'};continue}if(clockMismatch(parsed,temporal)){lastError={code:'clock_mismatch',reason:`daypart mismatch; current daypart is ${temporal.daypart}`};continue}if(achievementTooRecent(parsed.achievement,recentAchievements,ctx)){lastError={code:'recycled_achievement',reason:'achievement title was recycled'};continue}const shapeCheck=shapeQuality(parsed,shape,ctx,mode,recentPatterns);if(!shapeCheck.ok){lastError={code:'repetitive_body',reason:shapeCheck.reason};continue}lastPattern=shapeCheck.pattern;return res.status(200).json({commentary:parsed.commentary,title:parsed.headline,headline:parsed.headline,achievement:parsed.achievement,performanceShape:shape.id,bodyPattern:lastPattern,apiVersion:API_VERSION})}
    return res.status(502).json({error:'Council returned an unusable transmission',code:lastError?.code||'quality_failure',reason:lastError?.reason||'quality failure',apiVersion:API_VERSION});
  }catch(e){return res.status(e?.status||500).json({error:'Council Intelligence malfunction',code:e?.code||'server_error',apiVersion:API_VERSION})}
};
